const forms = require("@tailwindcss/forms");
const containerQueries = require("@tailwindcss/container-queries");

module.exports = {
  darkMode: "class",
  content: ["./frontend/index.html", "./frontend/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        background: "rgb(var(--rgb-background) / <alpha-value>)",
        "inverse-primary": "#6a5f00",
        "primary-fixed": "#fde403",
        tertiary: "#fbfffe",
        outline: "#979177",
        "on-secondary": "#313030",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#504700",
        "on-tertiary-container": "#006f72",
        "on-tertiary-fixed-variant": "#004f51",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#00dce1",
        "on-background": "rgb(var(--rgb-on-surface) / <alpha-value>)",
        "surface-tint": "#dec800",
        "primary-fixed-dim": "#dec800",
        "on-surface": "rgb(var(--rgb-on-surface) / <alpha-value>)",
        "surface-container-low": "rgb(var(--rgb-surface-low) / <alpha-value>)",
        "on-tertiary": "#003738",
        "surface-container": "rgb(var(--rgb-surface-container) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--rgb-on-surface-variant) / <alpha-value>)",
        "on-primary-container": "#706400",
        "on-error": "#690005",
        "surface-container-high": "rgb(var(--rgb-surface-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--rgb-surface-highest) / <alpha-value>)",
        error: "rgb(var(--rgb-error) / <alpha-value>)",
        primary: "#fffeff",
        "outline-variant": "rgb(var(--rgb-outline) / <alpha-value>)",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-lowest": "rgb(var(--rgb-surface-lowest) / <alpha-value>)",
        "inverse-surface": "#e5e2e1",
        surface: "rgb(var(--rgb-surface) / <alpha-value>)",
        "tertiary-container": "#04faff",
        "on-tertiary-fixed": "#002021",
        "tertiary-fixed": "#2dfaff",
        "surface-variant": "#353534",
        "on-primary": "#373100",
        "primary-container": "rgb(var(--rgb-primary) / <alpha-value>)",
        "inverse-on-surface": "#313030",
        secondary: "#c8c6c5",
        "on-secondary-container": "#b7b5b4",
        "on-primary-fixed": "#201c00",
        "secondary-container": "#474746",
        "surface-dim": "rgb(var(--rgb-surface) / <alpha-value>)",
        "surface-bright": "rgb(var(--rgb-surface-bright) / <alpha-value>)",
        "secondary-fixed": "#e5e2e1",
      },
      fontFamily: {
        body: "var(--font-family-body)",
        label: "var(--font-family-body)",
        mono: "var(--font-family-mono)",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [forms, containerQueries],
};
