const assert = require("node:assert/strict");
const path = require("node:path");
const { pathToFileURL } = require("node:url");
const test = require("node:test");

test("Advisor SQL uses a new editor tab and is never executed", async () => {
  const previousWindow = global.window;
  global.window = { setTimeout() {} };

  try {
    const store = await import(
      `${pathToFileURL(path.resolve(__dirname, "../frontend/js/store.js")).href}?advisor-editor-insert`
    );

    store.setCurrentQuery("SELECT 1;");
    const initialTabCount = store.getState().editor.queryTabs.length;
    const inserted = await store.insertAdvisorQuery(
      'BEGIN TRANSACTION;\n\nCREATE INDEX IF NOT EXISTS "idx_users_email"\nON "users" ("email");\n\nCOMMIT;',
      { title: "email is not indexed" }
    );
    const editor = store.getState().editor;
    const activeTab = editor.queryTabs.find((tab) => tab.id === editor.activeQueryTabId);

    assert.equal(inserted, true);
    assert.equal(editor.queryTabs.length, initialTabCount + 1);
    assert.equal(activeTab.origin, "Generated by Advisor");
    assert.equal(activeTab.title, "email is not indexed");
    assert.match(activeTab.sqlText, /CREATE INDEX/);
    assert.equal(editor.result, null);
    assert.equal(editor.lastExecutedSql, "");
    assert.equal(editor.executing, false);
  } finally {
    global.window = previousWindow;
  }
});

test("Advisor SQL reuses an already empty editor tab", async () => {
  const previousWindow = global.window;
  global.window = { setTimeout() {} };

  try {
    const store = await import(
      `${pathToFileURL(path.resolve(__dirname, "../frontend/js/store.js")).href}?advisor-editor-reuse`
    );
    const initialTabCount = store.getState().editor.queryTabs.length;

    await store.insertAdvisorQuery("BEGIN TRANSACTION;\nCOMMIT;", { title: "Safe fix" });

    const editor = store.getState().editor;
    assert.equal(editor.queryTabs.length, initialTabCount);
    assert.equal(editor.queryTabs[0].origin, "Generated by Advisor");
    assert.equal(editor.sqlText, "BEGIN TRANSACTION;\nCOMMIT;");
  } finally {
    global.window = previousWindow;
  }
});
