const assert = require("node:assert/strict");
const path = require("node:path");
const { pathToFileURL } = require("node:url");
const test = require("node:test");

let queryEditorModulePromise = null;

function loadQueryEditorModule() {
  if (!queryEditorModulePromise) {
    queryEditorModulePromise = import(
      pathToFileURL(path.resolve(__dirname, "../frontend/js/components/queryEditor.js")).href
    );
  }

  return queryEditorModulePromise;
}

test("query editor groups editor actions in a reusable dropdown", async () => {
  const { renderQueryEditor } = await loadQueryEditorModule();
  const markup = renderQueryEditor({ query: "select * from companies;" });

  assert.match(markup, /data-dropdown-button/);
  assert.match(markup, /Editor actions/);
  assert.match(markup, /data-action="format-current-query"/);
  assert.match(markup, /data-action="clear-query"/);
  assert.match(markup, /data-action="copy-current-query"/);
  assert.match(markup, /Copy to Clipboard/);
});

test("query editor renders Advisor query tabs with their origin", async () => {
  const { renderQueryEditor } = await loadQueryEditorModule();
  const markup = renderQueryEditor({
    query: 'CREATE INDEX "idx_users_email" ON "users" ("email");',
    queryTabs: [
      { id: "query-1", title: "Query 1", sqlText: "SELECT 1;", origin: "" },
      {
        id: "advisor-1",
        title: "email is not indexed",
        sqlText: 'CREATE INDEX "idx_users_email" ON "users" ("email");',
        origin: "Generated by Advisor",
      },
    ],
    activeQueryTabId: "advisor-1",
  });

  assert.match(markup, /role="tablist"/);
  assert.match(markup, /data-action="select-editor-query-tab"/);
  assert.match(markup, /data-tab-id="advisor-1"/);
  assert.match(markup, /Generated by Advisor/);
  assert.match(markup, /aria-selected="true"/);
});
