const assert = require("node:assert/strict");
const test = require("node:test");
const Database = require("better-sqlite3");

const {
  TableAdvisorService,
  analyzeTable,
  calculateScore,
  quoteIdentifier,
} = require("../server/services/sqlite/tableAdvisor");

function withDatabase(callback) {
  const db = new Database(":memory:");

  try {
    return callback(db);
  } finally {
    db.close();
  }
}

function getIssue(result, id) {
  return (result.issues ?? []).find((issue) => issue.id === id);
}

test("table advisor reports a missing primary key", () => {
  withDatabase((db) => {
    db.exec("CREATE TABLE events (name TEXT)");

    const result = analyzeTable(db, "events");
    const issue = getIssue(result, "schema:missing-primary-key");

    assert.equal(issue?.severity, "critical");
    assert.equal(issue?.category, "schema");
    assert.equal(issue?.risk, "high");
  });
});

test("table advisor suggests a unique index for unique email values", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL);
      INSERT INTO users (email) VALUES ('a@example.com'), ('b@example.com');
    `);

    const result = analyzeTable(db, "users");
    const issue = getIssue(result, "constraints:email:missing-unique-index");

    assert.equal(issue?.severity, "warning");
    assert.match(issue?.sql ?? "", /CREATE UNIQUE INDEX/);
    assert.match(issue?.sql ?? "", /"email"/);
    assert.match(issue?.sql ?? "", /^BEGIN TRANSACTION;/);
    assert.equal(issue?.fixAvailable, true);
    assert.equal(issue?.queryOrigin, "Generated by Advisor");
    assert.deepEqual(issue?.affectedObjects.columns, ["email"]);
    assert.ok(issue?.warnings.some((warning) => /database schema/i.test(warning)));

    db.exec(issue.sql);
    db.exec(issue.sql);
    assert.ok(
      db.prepare("PRAGMA index_list(\"users\")").all().some((index) => index.name === "idx_users_email_unique")
    );
  });
});

test("table advisor reports duplicate emails without suggesting a unique index", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL);
      INSERT INTO users (email) VALUES ('a@example.com'), ('a@example.com'), ('b@example.com');
    `);

    const result = analyzeTable(db, "users");

    assert.ok(getIssue(result, "data-quality:email:duplicate-values"));
    assert.equal(getIssue(result, "constraints:email:missing-unique-index"), undefined);
  });
});

test("table advisor does not present an observed enum as an executable CHECK migration", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE tasks (id INTEGER PRIMARY KEY, status TEXT NOT NULL);
      INSERT INTO tasks (status) VALUES ('open'), ('closed'), ('open');
    `);

    const result = analyzeTable(db, "tasks");
    const issue = getIssue(result, "constraints:status:check-constraint");

    assert.equal(issue?.severity, "info");
    assert.equal(issue?.risk, "high");
    assert.equal(issue?.fixAvailable, false);
    assert.equal(issue?.sql, undefined);
    assert.match(issue?.fixUnavailableReason ?? "", /Observed values do not prove/);
  });
});

test("table advisor suggests an index for foreign-key-like columns", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE comments (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, body TEXT);
      INSERT INTO comments (user_id, body) VALUES (1, 'one'), (2, 'two');
    `);

    const result = analyzeTable(db, "comments");
    const issue = getIssue(result, "performance:user_id:missing-index");

    assert.equal(issue?.severity, "warning");
    assert.equal(issue?.risk, "low");
    assert.match(issue?.sql ?? "", /CREATE INDEX/);
    db.exec(issue.sql);
  });
});

test("table advisor explains why created_at default changes need a complete rebuild", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE notes (id INTEGER PRIMARY KEY, created_at TEXT NOT NULL);
      INSERT INTO notes (created_at) VALUES ('2026-06-28T10:00:00Z');
    `);

    const result = analyzeTable(db, "notes");
    const issue = getIssue(result, "schema:created_at:missing-created-default");

    assert.equal(issue?.severity, "warning");
    assert.equal(issue?.fixAvailable, false);
    assert.equal(issue?.sql, undefined);
    assert.match(issue?.fixUnavailableReason ?? "", /complete rebuild/);
  });
});

test("table advisor detects empty text strings", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE contacts (id INTEGER PRIMARY KEY, email TEXT);
      INSERT INTO contacts (email) VALUES (''), ('a@example.com');
    `);

    const result = analyzeTable(db, "contacts");
    const issue = getIssue(result, "data-quality:email:empty-strings");

    assert.equal(issue?.severity, "critical");
    assert.equal(issue?.destructive, true);
    assert.equal(issue?.backupRecommended, true);
    assert.match(issue?.sql ?? "", /UPDATE/);
    assert.match(issue?.sql ?? "", /NULL/);
    db.exec(issue.sql);
    assert.equal(db.prepare("SELECT COUNT(*) AS count FROM contacts WHERE email IS NULL").get().count, 1);
  });
});

test("table advisor does not suggest NULL cleanup for a NOT NULL column", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE contacts (id INTEGER PRIMARY KEY, email TEXT NOT NULL);
      INSERT INTO contacts (email) VALUES (''), ('a@example.com');
    `);

    const issue = getIssue(analyzeTable(db, "contacts"), "data-quality:email:empty-strings");

    assert.equal(issue?.fixAvailable, false);
    assert.equal(issue?.sql, undefined);
    assert.match(issue?.fixUnavailableReason ?? "", /NOT NULL/);
  });
});

test("table advisor does not suggest cleanup that could violate CHECK constraints", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE contacts (
        id INTEGER PRIMARY KEY,
        email TEXT CHECK(email IS NOT NULL)
      );
      INSERT INTO contacts (email) VALUES (''), ('a@example.com');
    `);

    const issue = getIssue(analyzeTable(db, "contacts"), "data-quality:email:empty-strings");

    assert.equal(issue?.fixAvailable, false);
    assert.match(issue?.fixUnavailableReason ?? "", /CHECK constraints/);
  });
});

test("table advisor does not suggest cleanup with unexplained trigger side effects", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE contacts (id INTEGER PRIMARY KEY, email TEXT);
      CREATE TABLE contact_audit (contact_id INTEGER);
      CREATE TRIGGER audit_contacts AFTER UPDATE ON contacts
      BEGIN
        INSERT INTO contact_audit (contact_id) VALUES (NEW.id);
      END;
      INSERT INTO contacts (email) VALUES (''), ('a@example.com');
    `);

    const issue = getIssue(analyzeTable(db, "contacts"), "data-quality:email:empty-strings");

    assert.equal(issue?.fixAvailable, false);
    assert.match(issue?.fixUnavailableReason ?? "", /trigger/i);
  });
});

test("table advisor avoids schema-wide index name collisions", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE archived_comments (id INTEGER PRIMARY KEY, user_id INTEGER);
      CREATE INDEX idx_comments_user_id ON archived_comments(user_id);
      CREATE TABLE comments (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL);
      INSERT INTO comments (user_id) VALUES (1), (2);
    `);

    const issue = getIssue(analyzeTable(db, "comments"), "performance:user_id:missing-index");

    assert.match(issue?.sql ?? "", /"idx_comments_user_id_2"/);
    assert.deepEqual(issue?.affectedObjects.indexes, ["idx_comments_user_id_2"]);
    db.exec(issue.sql);
  });
});

test("table advisor quotes unusual schema identifiers in executable fixes", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE "order"" items" (
        "id" INTEGER PRIMARY KEY,
        "user""_id" INTEGER NOT NULL
      );
      INSERT INTO "order"" items" ("user""_id") VALUES (1), (2);
    `);

    const issue = getIssue(
      analyzeTable(db, 'order" items'),
      'performance:user"_id:missing-index'
    );

    assert.equal(issue?.fixAvailable, true);
    assert.match(issue?.sql ?? "", /ON "order"" items" \("user""_id"\)/);
    db.exec(issue.sql);
  });
});

test("table advisor emits a complete, idempotent updated_at trigger transaction", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE notes (
        id INTEGER PRIMARY KEY,
        body TEXT,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      INSERT INTO notes (body) VALUES ('before');
    `);

    const issue = getIssue(analyzeTable(db, "notes"), "schema:updated_at:updated-at-maintenance");

    assert.equal(issue?.fixAvailable, true);
    assert.equal(issue?.destructive, false);
    assert.match(issue?.sql ?? "", /^BEGIN TRANSACTION;/);
    assert.match(issue?.sql ?? "", /CREATE TRIGGER IF NOT EXISTS/);
    db.exec(issue.sql);
    db.exec(issue.sql);
    assert.equal(
      db.prepare("SELECT COUNT(*) AS count FROM sqlite_schema WHERE type = 'trigger'").get().count,
      1
    );
  });
});

test("table advisor respects existing triggers when considering updated_at maintenance", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE notes (
        id INTEGER PRIMARY KEY,
        body TEXT,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TRIGGER existing_notes_trigger AFTER UPDATE ON notes BEGIN SELECT 1; END;
    `);

    const issue = getIssue(analyzeTable(db, "notes"), "schema:updated_at:updated-at-maintenance");

    assert.equal(issue?.fixAvailable, false);
    assert.equal(issue?.sql, undefined);
    assert.match(issue?.fixUnavailableReason ?? "", /Existing triggers/);
  });
});

test("table advisor protects internal SQLite tables", () => {
  withDatabase((db) => {
    db.exec("CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)");
    const result = analyzeTable(db, "sqlite_sequence");

    assert.equal(result.issues.length, 1);
    assert.equal(result.issues[0].fixAvailable, false);
    assert.equal(result.issues[0].sql, undefined);
    assert.match(result.issues[0].fixUnavailableReason, /never generates changes/i);
  });
});

test("table advisor score uses deterministic penalties", () => {
  const score = calculateScore([
    { severity: "critical" },
    { severity: "warning" },
    { severity: "info" },
  ]);

  assert.equal(score, 70);
});

test("table advisor exposes safe SQLite identifier quoting", () => {
  assert.equal(quoteIdentifier('we"ird'), '"we""ird"');
});

test("table advisor does not recommend a unique index that already exists", () => {
  withDatabase((db) => {
    db.exec(`
      CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL);
      CREATE UNIQUE INDEX idx_users_email_unique ON users (email);
      INSERT INTO users (email) VALUES ('a@example.com'), ('b@example.com');
    `);

    const result = new TableAdvisorService().analyzeTable(db, "users");

    assert.equal(getIssue(result, "constraints:email:missing-unique-index"), undefined);
  });
});
