const fs = require("node:fs");
const path = require("node:path");
const { fileURLToPath } = require("node:url");
const { detectQueryType } = require("../storage/queryHistoryUtils");
const { ConflictError, NotFoundError, ValidationError, mapSqliteError } = require("../../utils/errors");
const { quoteIdentifier } = require("../../utils/identifier");
const { getRawStructureEntries, getTableDetail } = require("./introspection");
const { serializeRow } = require("../../utils/sqliteTypes");

const MEDIA_ROWID_ALIAS = "__sqlite_hub_media_rowid";
const TAG_ROWID_ALIAS = "__sqlite_hub_tag_rowid";
const DEFAULT_TAG_TABLE_NAME = "media_tags";
const DEFAULT_TAG_TABLE_CREATE_SQL = [
  'CREATE TABLE "media_tags" (',
  "  id INTEGER PRIMARY KEY,",
  "  name TEXT NOT NULL UNIQUE,",
  "  isParentTag INTEGER NOT NULL DEFAULT 0,",
  "  parentTagId INTEGER REFERENCES media_tags(id) ON DELETE SET NULL",
  ")",
].join("\n");
const DEFAULT_MAPPING_TABLE_NAME = "media_asset_tags";
const DEFAULT_MAPPING_TABLE_CREATE_SQL = [
  "CREATE TABLE media_asset_tags (",
  "  media_asset_id INTEGER NOT NULL,",
  "  media_tag_id INTEGER NOT NULL,",
  "  PRIMARY KEY (media_asset_id, media_tag_id),",
  "  FOREIGN KEY (media_asset_id) REFERENCES media_assets(id) ON DELETE CASCADE,",
  "  FOREIGN KEY (media_tag_id) REFERENCES media_tags(id) ON DELETE CASCADE",
  ")",
].join("\n");
const PATH_COLUMN_PATTERN = /(path|file|filename|filepath|uri|url|src|source|image|photo|media|asset|video|audio)/i;
const BOOLEAN_COLUMN_PATTERN =
  /(^is_|^is[A-Z]|^has_|^has[A-Z]|^can_|^can[A-Z]|tagged|processed|done|reviewed|complete|completed|flag|enabled|active|checked)/i;
const TAG_TABLE_PATTERN = /(tag|label|category|keyword)/i;
const TAG_LABEL_PATTERN = /^(name|label|title|tag|keyword)$/i;
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp", ".svg"]);
const VIDEO_EXTENSIONS = new Set([".mp4", ".mov", ".m4v", ".webm", ".avi", ".mkv"]);
const AUDIO_EXTENSIONS = new Set([".mp3", ".wav", ".ogg", ".oga", ".m4a", ".aac", ".flac"]);
const PARENT_TAG_FLAG_COLUMN = "isParentTag";
const PARENT_TAG_ID_COLUMN = "parentTagId";

function normalizeConfigValue(value) {
  return String(value ?? "").trim();
}

function normalizeMediaTaggingConfig(config = {}) {
  return {
    tagTable: DEFAULT_TAG_TABLE_NAME,
    mediaTable: normalizeConfigValue(config.mediaTable),
    pathColumn: normalizeConfigValue(config.pathColumn),
    taggedColumn: normalizeConfigValue(config.taggedColumn),
    untaggedQuery: String(config.untaggedQuery ?? "").trim(),
    taggedQuery: String(config.taggedQuery ?? "").trim(),
    mappingTable: DEFAULT_MAPPING_TABLE_NAME,
  };
}

function buildIssue(scope, code, message, severity = "alert") {
  return {
    scope,
    code,
    message,
    severity,
  };
}

function getVisibleColumns(tableDetail) {
  return (tableDetail?.columns ?? []).filter(
    (column) => column.visible !== false && !column.generated
  );
}

function isLikelyPathColumn(column) {
  return PATH_COLUMN_PATTERN.test(String(column?.name ?? ""));
}

function isLikelyBooleanColumn(column) {
  const declaredType = String(column?.declaredType ?? "").toUpperCase();

  if (declaredType.includes("BOOL")) {
    return true;
  }

  if (BOOLEAN_COLUMN_PATTERN.test(String(column?.name ?? ""))) {
    return true;
  }

  return false;
}

function getColumnInputKind(column) {
  const declaredType = String(column?.declaredType ?? "").toUpperCase();
  const affinity = String(column?.affinity ?? "").toUpperCase();

  if (declaredType.includes("BOOL") || BOOLEAN_COLUMN_PATTERN.test(String(column?.name ?? ""))) {
    return "checkbox";
  }

  if (affinity === "INTEGER" || affinity === "REAL" || affinity === "NUMERIC") {
    return "number";
  }

  return "text";
}

function isAutoGeneratedPrimaryKey(tableDetail, column) {
  if (!column || column.primaryKeyPosition !== 1) {
    return false;
  }

  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  return (
    identity.type === "primaryKey" &&
    identity.columns.length === 1 &&
    identity.columns[0] === column.name &&
    !tableDetail.withoutRowId &&
    String(column.declaredType ?? "").toUpperCase() === "INTEGER"
  );
}

function canOmitPrimaryKeyValue(tableDetail, column) {
  if (!column || column.primaryKeyPosition !== 1 || tableDetail?.withoutRowId) {
    return false;
  }

  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (
    identity.type !== "primaryKey" ||
    identity.columns.length !== 1 ||
    identity.columns[0] !== column.name
  ) {
    return false;
  }

  return isAutoGeneratedPrimaryKey(tableDetail, column) || !column.notNull;
}

function canBackfillPrimaryKeyFromRowId(tableDetail, column) {
  return (
    canOmitPrimaryKeyValue(tableDetail, column) &&
    !isAutoGeneratedPrimaryKey(tableDetail, column) &&
    column.defaultValue === null
  );
}

function getRequiredInsertColumns(tableDetail, providedColumns = []) {
  const providedSet = new Set(providedColumns);

  return getVisibleColumns(tableDetail).filter((column) => {
    if (providedSet.has(column.name)) {
      return false;
    }

    if (canOmitPrimaryKeyValue(tableDetail, column)) {
      return false;
    }

    if (column.primaryKeyPosition > 0) {
      return column.defaultValue === null;
    }

    return column.notNull && column.defaultValue === null;
  });
}

function getTableCatalog(db) {
  return getRawStructureEntries(db)
    .filter((entry) => entry.type === "table")
    .map((entry) => getTableDetail(db, entry.name, { includeRowCount: false }));
}

function toClientTableSummary(tableDetail) {
  const columns = getVisibleColumns(tableDetail).map((column) => ({
    name: column.name,
    declaredType: column.declaredType,
    affinity: column.affinity,
    notNull: column.notNull,
    defaultValue: column.defaultValue,
    primaryKeyPosition: column.primaryKeyPosition,
    inputKind: getColumnInputKind(column),
    pathCandidate: isLikelyPathColumn(column),
    booleanCandidate: isLikelyBooleanColumn(column),
  }));

  return {
    name: tableDetail.name,
    withoutRowId: tableDetail.withoutRowId,
    identityStrategy: tableDetail.identityStrategy,
    columns,
    pathCandidates: columns.filter((column) => column.pathCandidate).map((column) => column.name),
    booleanCandidates: columns
      .filter((column) => column.booleanCandidate)
      .map((column) => column.name),
  };
}

function findTableDetail(tableCatalog, tableName) {
  return tableCatalog.find((table) => table.name === tableName) ?? null;
}

function chooseBestPathColumn(tableDetail) {
  const visibleColumns = getVisibleColumns(tableDetail);

  return (
    visibleColumns.find((column) => /^(path|file_path|filepath|filename|url|uri|src)$/i.test(column.name))
      ?.name ??
    visibleColumns.find((column) => isLikelyPathColumn(column))?.name ??
    visibleColumns.find((column) => ["TEXT", "BLOB"].includes(column.affinity))?.name ??
    ""
  );
}

function chooseBestBooleanColumn(tableDetail) {
  const visibleColumns = getVisibleColumns(tableDetail);

  return (
    visibleColumns.find((column) => /^(is_)?tagged$/i.test(column.name))?.name ??
    visibleColumns.find((column) => /(processed|done|reviewed|completed)/i.test(column.name))?.name ??
    visibleColumns.find((column) => isLikelyBooleanColumn(column))?.name ??
    ""
  );
}

function getMediaIdentityQueryColumns(tableDetail) {
  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (identity.type === "rowid") {
    return [MEDIA_ROWID_ALIAS];
  }

  return [...(identity.columns ?? [])];
}

function buildMediaRowIdentity(tableDetail, row) {
  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (!row || typeof row !== "object") {
    return null;
  }

  if (identity.type === "rowid") {
    if (!Object.prototype.hasOwnProperty.call(row, MEDIA_ROWID_ALIAS)) {
      return null;
    }

    return {
      kind: "rowid",
      values: {
        rowid: row[MEDIA_ROWID_ALIAS],
      },
    };
  }

  if (identity.type === "primaryKey") {
    const columns = [...(identity.columns ?? [])];

    if (!columns.length) {
      return null;
    }

    return {
      kind: "primaryKey",
      columns,
      values: Object.fromEntries(columns.map((columnName) => [columnName, row[columnName] ?? null])),
    };
  }

  return null;
}

function getTagIdentityQueryColumns(tableDetail) {
  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (identity.type === "rowid") {
    return [TAG_ROWID_ALIAS];
  }

  return [...(identity.columns ?? [])];
}

function getSingleTagIdentityColumn(tableDetail) {
  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (identity.type === "primaryKey" && identity.columns.length === 1) {
    return identity.columns[0];
  }

  return null;
}

function buildOrderByClause(tableDetail, rowIdAlias) {
  const identity = tableDetail?.identityStrategy ?? { type: "none", columns: [] };

  if (identity.type === "primaryKey" && identity.columns.length) {
    return `ORDER BY ${identity.columns.map((column) => quoteIdentifier(column)).join(", ")} ASC`;
  }

  if (identity.type === "rowid" && rowIdAlias) {
    return `ORDER BY ${quoteIdentifier(rowIdAlias)} ASC`;
  }

  return "";
}

function buildDefaultMediaQueries(tableDetail, config = {}) {
  if (!tableDetail || !config.taggedColumn) {
    return {
      untaggedQuery: "",
      taggedQuery: "",
    };
  }

  const selectionPrefix =
    tableDetail.identityStrategy?.type === "rowid"
      ? `SELECT rowid AS ${quoteIdentifier(MEDIA_ROWID_ALIAS)}, *`
      : "SELECT *";
  const tableSql = `${selectionPrefix} FROM ${quoteIdentifier(tableDetail.name)}`;
  const taggedColumnSql = quoteIdentifier(config.taggedColumn);
  const orderByClause = buildOrderByClause(tableDetail, MEDIA_ROWID_ALIAS);
  const orderSegment = orderByClause ? `\n${orderByClause}` : "";

  return {
    untaggedQuery: `${tableSql}\nWHERE COALESCE(${taggedColumnSql}, 0) = 0${orderSegment}`,
    taggedQuery: `${tableSql}\nWHERE COALESCE(${taggedColumnSql}, 0) = 1${orderSegment}`,
  };
}

function stripTrailingSemicolons(query = "") {
  return String(query).trim().replace(/;+\s*$/g, "");
}

function isSelectQuery(query = "") {
  return detectQueryType(stripTrailingSemicolons(query)) === "select";
}

function buildWrappedQuery(query) {
  return stripTrailingSemicolons(query);
}

function getQueryOutputColumns(db, query) {
  const statement = db.prepare(
    `SELECT * FROM (${buildWrappedQuery(query)}) AS media_tagging_source LIMIT 0`
  );

  return statement.columns().map((column) => column.name);
}

function countQueryRows(db, query) {
  const row = db
    .prepare(`SELECT COUNT(*) AS count FROM (${buildWrappedQuery(query)}) AS media_tagging_source`)
    .get();

  return Number(row?.count ?? 0);
}

function encodeKey(values = []) {
  return JSON.stringify(values);
}

function decodeKey(key, expectedLength) {
  const parsed = JSON.parse(String(key ?? ""));

  if (!Array.isArray(parsed) || parsed.length !== expectedLength) {
    throw new ValidationError("Stored media tagging key is invalid.");
  }

  return parsed;
}

function buildKeyFromRow(row, columns = []) {
  return encodeKey(columns.map((column) => row?.[column] ?? null));
}

function buildExcludedKeyClause(columns = [], keys = []) {
  if (!columns.length || !Array.isArray(keys) || !keys.length) {
    return {
      sql: "",
      params: [],
    };
  }

  const decodedKeys = keys
    .map((key) => {
      try {
        return decodeKey(key, columns.length);
      } catch {
        return null;
      }
    })
    .filter(Boolean);

  if (!decodedKeys.length) {
    return {
      sql: "",
      params: [],
    };
  }

  return {
    sql: decodedKeys
      .map(
        () =>
          `(${columns.map((column) => `${quoteIdentifier(column)} = ?`).join(" AND ")})`
      )
      .join(" OR "),
    params: decodedKeys.flat(),
  };
}

function buildKeyWhereClause(columns = [], values = []) {
  if (!Array.isArray(columns) || !columns.length) {
    throw new ValidationError("A stable key is required for this operation.");
  }

  if (!Array.isArray(values) || values.length !== columns.length) {
    throw new ValidationError("The provided key does not match the expected SQLite columns.");
  }

  return {
    sql: columns
      .map((column) =>
        column === TAG_ROWID_ALIAS || column === MEDIA_ROWID_ALIAS
          ? "rowid = ?"
          : `${quoteIdentifier(column)} = ?`
      )
      .join(" AND "),
    params: values,
  };
}

function getTagLabelColumns(tableDetail) {
  const visibleColumns = getVisibleColumns(tableDetail).filter(
    (column) =>
      ![PARENT_TAG_FLAG_COLUMN, PARENT_TAG_ID_COLUMN].includes(String(column?.name ?? ""))
  );
  const preferredColumns = visibleColumns.filter((column) => TAG_LABEL_PATTERN.test(column.name));

  if (preferredColumns.length) {
    return preferredColumns.map((column) => column.name);
  }

  const textColumns = visibleColumns.filter((column) =>
    ["TEXT", "NUMERIC", "INTEGER"].includes(String(column.affinity ?? "").toUpperCase())
  );

  if (textColumns.length) {
    return textColumns.slice(0, 2).map((column) => column.name);
  }

  return visibleColumns.slice(0, 2).map((column) => column.name);
}

function getParentTagFeatureColumns(tableDetail) {
  const visibleColumns = getVisibleColumns(tableDetail);
  const flagColumn =
    visibleColumns.find((column) => column.name === PARENT_TAG_FLAG_COLUMN) ?? null;
  const parentIdColumn =
    visibleColumns.find((column) => column.name === PARENT_TAG_ID_COLUMN) ?? null;

  if (!flagColumn || !parentIdColumn) {
    return null;
  }

  return {
    flagColumn,
    parentIdColumn,
  };
}

function buildTagLabel(row, labelColumns = []) {
  const label = labelColumns
    .map((column) => row?.[column])
    .filter((value) => value !== null && value !== undefined && String(value).trim() !== "")
    .map((value) => String(value))
    .join(" / ");

  return label || "Untitled tag";
}

function chooseSuggestedTagTable(tableCatalog) {
  const insertableTables = tableCatalog.filter((table) =>
    getVisibleColumns(table).some((column) => column.primaryKeyPosition === 0)
  );

  return (
    insertableTables.find((table) => TAG_TABLE_PATTERN.test(table.name)) ??
    insertableTables.find((table) => getVisibleColumns(table).length > 0) ??
    null
  );
}

function chooseSuggestedMediaTable(tableCatalog) {
  return (
    tableCatalog.find((table) => chooseBestPathColumn(table) && chooseBestBooleanColumn(table)) ??
    tableCatalog.find((table) => chooseBestPathColumn(table)) ??
    null
  );
}

function findMappingMatches(tableCatalog, mediaTableName, tagTableName) {
  const candidates = [];
  const ambiguousTables = [];

  if (!mediaTableName || !tagTableName) {
    return { candidates, ambiguousTables };
  }

  tableCatalog.forEach((tableDetail) => {
    if (tableDetail.name === mediaTableName || tableDetail.name === tagTableName) {
      return;
    }

    const mediaForeignKeys = tableDetail.foreignKeys.filter(
      (foreignKey) => foreignKey.referencedTable === mediaTableName
    );
    const tagForeignKeys = tableDetail.foreignKeys.filter(
      (foreignKey) => foreignKey.referencedTable === tagTableName
    );

    if (!mediaForeignKeys.length || !tagForeignKeys.length) {
      return;
    }

    if (mediaForeignKeys.length !== 1 || tagForeignKeys.length !== 1) {
      ambiguousTables.push({
        tableName: tableDetail.name,
        mediaForeignKeyCount: mediaForeignKeys.length,
        tagForeignKeyCount: tagForeignKeys.length,
      });
      return;
    }

    const mediaForeignKey = mediaForeignKeys[0];
    const tagForeignKey = tagForeignKeys[0];
    const providedColumns = [
      ...mediaForeignKey.mappings.map((mapping) => mapping.from),
      ...tagForeignKey.mappings.map((mapping) => mapping.from),
    ];
    const requiredColumns = getRequiredInsertColumns(tableDetail, providedColumns);

    candidates.push({
      tableName: tableDetail.name,
      mediaForeignKey,
      tagForeignKey,
      requiredColumns: requiredColumns.map((column) => ({
        name: column.name,
        declaredType: column.declaredType,
        affinity: column.affinity,
        notNull: column.notNull,
        defaultValue: column.defaultValue,
      })),
    });
  });

  return {
    candidates,
    ambiguousTables,
  };
}

function inferSelectedMapping(mappingCandidates, requestedTableName) {
  if (requestedTableName) {
    const requestedCandidate =
      mappingCandidates.find((candidate) => candidate.tableName === requestedTableName) ?? null;

    return {
      selectedCandidate: requestedCandidate,
      selectedTableName: requestedTableName,
      autoDetected: false,
    };
  }

  if (mappingCandidates.length === 1) {
    return {
      selectedCandidate: mappingCandidates[0],
      selectedTableName: mappingCandidates[0].tableName,
      autoDetected: true,
    };
  }

  return {
    selectedCandidate: null,
    selectedTableName: "",
    autoDetected: false,
  };
}

function buildSuggestedConfig(tableCatalog) {
  const suggestedMediaTable = chooseSuggestedMediaTable(tableCatalog);
  const config = normalizeMediaTaggingConfig({
    mediaTable: suggestedMediaTable?.name ?? "",
    pathColumn: suggestedMediaTable ? chooseBestPathColumn(suggestedMediaTable) : "",
    taggedColumn: suggestedMediaTable ? chooseBestBooleanColumn(suggestedMediaTable) : "",
  });
  const defaultQueries = suggestedMediaTable ? buildDefaultMediaQueries(suggestedMediaTable, config) : null;

  return {
    ...config,
    untaggedQuery: defaultQueries?.untaggedQuery ?? "",
    taggedQuery: defaultQueries?.taggedQuery ?? "",
    mappingTable: DEFAULT_MAPPING_TABLE_NAME,
  };
}

function resolveQueryColumnsOrIssue(db, query, scope, issues, label) {
  if (!query) {
    issues.push(buildIssue(scope, `${label}_QUERY_REQUIRED`, `${label} query is required.`));
    return null;
  }

  if (!isSelectQuery(query)) {
    issues.push(
      buildIssue(
        scope,
        `${label}_QUERY_INVALID`,
        `${label} query must be a SELECT statement or CTE that resolves to a SELECT.`
      )
    );
    return null;
  }

  try {
    return getQueryOutputColumns(db, query);
  } catch (error) {
    issues.push(
      buildIssue(
        scope,
        `${label}_QUERY_INVALID`,
        `${label} query could not be prepared: ${error.message}`
      )
    );
    return null;
  }
}

function inferPreviewKind(pathValue = "") {
  const normalizedPath = String(pathValue ?? "").trim().toLowerCase();
  const extension = path.extname(normalizedPath);

  if (IMAGE_EXTENSIONS.has(extension)) {
    return "image";
  }

  if (VIDEO_EXTENSIONS.has(extension)) {
    return "video";
  }

  if (AUDIO_EXTENSIONS.has(extension)) {
    return "audio";
  }

  if (/^https?:\/\//i.test(normalizedPath)) {
    return "link";
  }

  return "unknown";
}

class MediaTaggingService {
  constructor({ connectionManager, appStateStore }) {
    this.connectionManager = connectionManager;
    this.appStateStore = appStateStore;
  }

  getActiveConnection() {
    return this.connectionManager.getActiveConnection();
  }

  getActiveDatabaseKey() {
    const connection = this.getActiveConnection();
    return connection?.id ?? "";
  }

  getPersistedConfig() {
    return this.appStateStore.getMediaTaggingConfig(this.getActiveDatabaseKey());
  }

  saveConfig(config = {}, options = {}) {
    const normalizedConfig = normalizeMediaTaggingConfig(config);

    this.appStateStore.setMediaTaggingConfig(this.getActiveDatabaseKey(), normalizedConfig);

    return this.getViewState({
      config: normalizedConfig,
      skippedMediaKeys: options.skippedMediaKeys ?? [],
    });
  }

  createDefaultTagTable(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const tableCatalog = getTableCatalog(db);

    if (findTableDetail(tableCatalog, DEFAULT_TAG_TABLE_NAME)) {
      throw new ConflictError(`${DEFAULT_TAG_TABLE_NAME} already exists.`);
    }

    try {
      db.exec(DEFAULT_TAG_TABLE_CREATE_SQL);
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config: payload.config ?? this.getPersistedConfig()?.config ?? {},
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  createDefaultMappingTable(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const tableCatalog = getTableCatalog(db);

    if (findTableDetail(tableCatalog, DEFAULT_MAPPING_TABLE_NAME)) {
      throw new ConflictError(`${DEFAULT_MAPPING_TABLE_NAME} already exists.`);
    }

    try {
      db.exec(DEFAULT_MAPPING_TABLE_CREATE_SQL);
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config: payload.config ?? this.getPersistedConfig()?.config ?? {},
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  getViewState(options = {}) {
    const db = this.connectionManager.getActiveDatabase();
    const connection = this.getActiveConnection();
    const tableCatalog = getTableCatalog(db);
    const persisted = this.getPersistedConfig();
    const baseConfig =
      options.config ??
      persisted?.config ??
      buildSuggestedConfig(tableCatalog);
    const config = normalizeMediaTaggingConfig(baseConfig);
    const issues = [];
    const tagTableDetail = findTableDetail(tableCatalog, config.tagTable);
    const mediaTableDetail = findTableDetail(tableCatalog, config.mediaTable);
    const tagTableColumns = tagTableDetail
      ? getVisibleColumns(tagTableDetail)
          .filter((column) => column.primaryKeyPosition === 0)
          .map((column) => ({
            name: column.name,
            declaredType: column.declaredType,
            affinity: column.affinity,
            notNull: column.notNull,
            defaultValue: column.defaultValue,
            primaryKeyPosition: column.primaryKeyPosition,
            inputKind: getColumnInputKind(column),
            uiRole:
              column.name === PARENT_TAG_FLAG_COLUMN
                ? "parent-toggle"
                : column.name === PARENT_TAG_ID_COLUMN
                  ? "parent-select"
                  : null,
          }))
      : [];
    const tagInsertIssues = tagTableDetail
      ? getRequiredInsertColumns(
          tagTableDetail,
          tagTableColumns.map((column) => column.name)
        )
      : [];

    if (config.tagTable && !tagTableDetail) {
      issues.push(
        buildIssue("tags", "TAG_TABLE_NOT_FOUND", `Required tag table "${config.tagTable}" was not found.`)
      );
    }

    if (config.mediaTable && !mediaTableDetail) {
      issues.push(
        buildIssue(
          "tagging",
          "MEDIA_TABLE_NOT_FOUND",
          `Media table "${config.mediaTable}" no longer exists.`
        )
      );
    }

    if (tagInsertIssues.length) {
      issues.push(
        buildIssue(
          "tags",
          "TAG_TABLE_REQUIRES_EXTRA_COLUMNS",
          `Tag table "${tagTableDetail.name}" needs additional required columns that are not part of the generated form: ${tagInsertIssues
            .map((column) => column.name)
            .join(", ")}.`
        )
      );
    }

    const mediaPathCandidates = mediaTableDetail
      ? getVisibleColumns(mediaTableDetail)
          .filter((column) => isLikelyPathColumn(column))
          .map((column) => column.name)
      : [];
    const mediaBooleanCandidates = mediaTableDetail
      ? getVisibleColumns(mediaTableDetail)
          .filter((column) => isLikelyBooleanColumn(column))
          .map((column) => column.name)
      : [];

    if (mediaTableDetail && !mediaPathCandidates.length) {
      issues.push(
        buildIssue(
          "tagging",
          "PATH_COLUMN_NOT_DETECTED",
          `Media table "${mediaTableDetail.name}" has no obvious path column. Choose one manually.`
        )
      );
    }

    if (mediaTableDetail && !mediaBooleanCandidates.length) {
      issues.push(
        buildIssue(
          "tagging",
          "BOOLEAN_COLUMN_NOT_DETECTED",
          `Media table "${mediaTableDetail.name}" has no obvious boolean tagging column.`
        )
      );
    }

    const defaultQueries =
      mediaTableDetail && config.taggedColumn ? buildDefaultMediaQueries(mediaTableDetail, config) : null;

    if (!config.untaggedQuery && defaultQueries?.untaggedQuery) {
      config.untaggedQuery = defaultQueries.untaggedQuery;
    }

    if (!config.taggedQuery && defaultQueries?.taggedQuery) {
      config.taggedQuery = defaultQueries.taggedQuery;
    }

    const { candidates: mappingCandidates } = findMappingMatches(
      tableCatalog,
      config.mediaTable,
      config.tagTable
    );
    const inferredMapping = inferSelectedMapping(mappingCandidates, config.mappingTable);
    const requestedMappingTableDetail = findTableDetail(tableCatalog, config.mappingTable);

    if (config.mediaTable && config.tagTable && !requestedMappingTableDetail && !inferredMapping.selectedCandidate) {
      issues.push(
        buildIssue(
          "mapping",
          "MAPPING_TABLE_NOT_FOUND",
          `Required mapping table "${config.mappingTable}" was not found.`
        )
      );
    }

    if (config.mappingTable && requestedMappingTableDetail && !inferredMapping.selectedCandidate) {
      issues.push(
        buildIssue(
          "mapping",
          "MAPPING_TABLE_NOT_AVAILABLE",
          `Mapping table "${config.mappingTable}" does not link the selected media and tag tables.`
        )
      );
    }

    if (inferredMapping.selectedCandidate?.requiredColumns?.length) {
      issues.push(
        buildIssue(
          "mapping",
          "MAPPING_TABLE_REQUIRES_EXTRA_COLUMNS",
          `Mapping table "${inferredMapping.selectedCandidate.tableName}" requires additional mandatory columns: ${inferredMapping.selectedCandidate.requiredColumns
            .map((column) => column.name)
            .join(", ")}.`
        )
      );
    }

    config.mappingTable = inferredMapping.selectedTableName;

    const tagOptions = tagTableDetail
      ? this.loadTagOptions(db, tagTableDetail, inferredMapping.selectedCandidate, issues)
      : [];
    const workflow = this.buildWorkflowState({
      db,
      connection,
      config,
      mediaTableDetail,
      selectedMapping: inferredMapping.selectedCandidate,
      tagOptions,
      skippedMediaKeys: options.skippedMediaKeys ?? [],
      issues,
    });

    return {
      connection: connection
        ? {
            id: connection.id,
            label: connection.label,
            readOnly: Boolean(connection.readOnly),
          }
        : null,
      persistedConfig: persisted?.config ?? null,
      persistedAt: persisted?.updatedAt ?? null,
      config,
      suggestedConfig: buildSuggestedConfig(tableCatalog),
      schemaTables: tableCatalog.map((table) => toClientTableSummary(table)),
      tagTableColumns,
      mediaTableColumns: mediaTableDetail
        ? getVisibleColumns(mediaTableDetail).map((column) => ({
            name: column.name,
            declaredType: column.declaredType,
            affinity: column.affinity,
            notNull: column.notNull,
            defaultValue: column.defaultValue,
            primaryKeyPosition: column.primaryKeyPosition,
          }))
        : [],
      pathCandidates: mediaPathCandidates,
      booleanCandidates: mediaBooleanCandidates,
      defaultQueries: defaultQueries ?? {
        untaggedQuery: "",
        taggedQuery: "",
      },
      mappingCandidates: mappingCandidates.map((candidate) => ({
        tableName: candidate.tableName,
        mediaForeignKey: candidate.mediaForeignKey,
        tagForeignKey: candidate.tagForeignKey,
        requiredColumns: candidate.requiredColumns,
      })),
      mappingSelection: {
        selectedTableName: inferredMapping.selectedTableName,
        autoDetected: inferredMapping.autoDetected,
      },
      tags: tagOptions,
      workflow,
      issues,
    };
  }

  loadTagOptions(db, tagTableDetail, selectedMapping, issues) {
    const keyColumns = selectedMapping
      ? selectedMapping.tagForeignKey.mappings.map((mapping) => mapping.to)
      : getTagIdentityQueryColumns(tagTableDetail);

    if (!keyColumns.length) {
      issues.push(
        buildIssue(
          "tags",
          "TAG_IDENTITY_NOT_AVAILABLE",
          `Tag table "${tagTableDetail.name}" does not expose a stable key for selection.`
        )
      );
      return [];
    }

    const labelColumns = getTagLabelColumns(tagTableDetail);
    const selectionPrefix =
      tagTableDetail.identityStrategy?.type === "rowid"
        ? `SELECT rowid AS ${quoteIdentifier(TAG_ROWID_ALIAS)}, *`
        : "SELECT *";
    const orderByColumns = labelColumns.length ? labelColumns : keyColumns;
    const parentTagFeature = getParentTagFeatureColumns(tagTableDetail);
    const singleIdentityColumn = getSingleTagIdentityColumn(tagTableDetail);
    const rows = db
      .prepare(
        `${selectionPrefix} FROM ${quoteIdentifier(tagTableDetail.name)} ORDER BY ${orderByColumns
          .map((column) => quoteIdentifier(column))
          .join(", ")} ASC`
      )
      .all();

    const parentTagLabelById =
      parentTagFeature && singleIdentityColumn
        ? new Map(
            rows
              .filter((row) => Boolean(row?.[parentTagFeature.flagColumn.name]))
              .map((row) => [
                String(row?.[singleIdentityColumn] ?? ""),
                buildTagLabel(row, labelColumns),
              ])
          )
        : new Map();

    return rows.map((row) => {
      const identityValue = singleIdentityColumn ? row?.[singleIdentityColumn] ?? null : null;
      const parentTagId = parentTagFeature ? row?.[parentTagFeature.parentIdColumn.name] ?? null : null;
      const parentLookupKey =
        parentTagId === null || parentTagId === undefined || parentTagId === ""
          ? null
          : String(parentTagId);

      return {
        key: buildKeyFromRow(row, keyColumns),
        label: buildTagLabel(row, labelColumns),
        row: serializeRow(row),
        identityValue,
        isParentTag: parentTagFeature ? Boolean(row?.[parentTagFeature.flagColumn.name]) : false,
        parentTagId,
        parentTagLabel: parentLookupKey ? parentTagLabelById.get(parentLookupKey) ?? "" : "",
      };
    });
  }

  buildWorkflowState({
    db,
    connection,
    config,
    mediaTableDetail,
    selectedMapping,
    tagOptions,
    skippedMediaKeys,
    issues,
  }) {
    const workflow = {
      ready: false,
      canWrite: Boolean(connection) && !connection.readOnly,
      status: {
        taggedCount: 0,
        remainingCount: 0,
        totalCount: 0,
        ratioLabel: "0 / 0",
      },
      currentItem: null,
      selectedMappingTable: selectedMapping?.tableName ?? "",
      skippedCount: Array.isArray(skippedMediaKeys) ? skippedMediaKeys.length : 0,
      allRemainingSkipped: false,
    };

    if (!mediaTableDetail || !config.pathColumn || !config.taggedColumn || !config.tagTable) {
      return workflow;
    }

    const mediaColumns = new Set(getVisibleColumns(mediaTableDetail).map((column) => column.name));

    if (!mediaColumns.has(config.pathColumn)) {
      issues.push(
        buildIssue(
          "tagging",
          "PATH_COLUMN_INVALID",
          `Path column "${config.pathColumn}" is not part of media table "${mediaTableDetail.name}".`
        )
      );
      return workflow;
    }

    if (!mediaColumns.has(config.taggedColumn)) {
      issues.push(
        buildIssue(
          "tagging",
          "BOOLEAN_COLUMN_INVALID",
          `Tagging column "${config.taggedColumn}" is not part of media table "${mediaTableDetail.name}".`
        )
      );
      return workflow;
    }

    const untaggedColumns = resolveQueryColumnsOrIssue(
      db,
      config.untaggedQuery,
      "tagging",
      issues,
      "UNTAGGED"
    );
    const taggedColumns = resolveQueryColumnsOrIssue(
      db,
      config.taggedQuery,
      "tagging",
      issues,
      "TAGGED"
    );

    if (!untaggedColumns || !taggedColumns) {
      return workflow;
    }

    const requiredCurrentItemColumns = new Set([
      ...getMediaIdentityQueryColumns(mediaTableDetail),
      config.pathColumn,
      ...(selectedMapping
        ? selectedMapping.mediaForeignKey.mappings.map((mapping) => mapping.to)
        : []),
    ]);

    const missingColumns = [...requiredCurrentItemColumns].filter(
      (column) => !untaggedColumns.includes(column)
    );

    if (missingColumns.length) {
      issues.push(
        buildIssue(
          "tagging",
          "UNTAGGED_QUERY_MISSING_COLUMNS",
          `Untagged query must return: ${missingColumns.join(", ")}.`
        )
      );
      return workflow;
    }

    try {
      workflow.status.taggedCount = countQueryRows(db, config.taggedQuery);
      workflow.status.remainingCount = countQueryRows(db, config.untaggedQuery);
      workflow.status.totalCount =
        workflow.status.taggedCount + workflow.status.remainingCount;
      workflow.status.ratioLabel = `${workflow.status.taggedCount} / ${workflow.status.totalCount}`;
    } catch (error) {
      issues.push(
        buildIssue(
          "tagging",
          "TAGGING_STATUS_QUERY_FAILED",
          `Tagging status counts could not be calculated: ${error.message}`
        )
      );
      return workflow;
    }

    try {
      const currentRow = this.loadCurrentMediaRow(
        db,
        config.untaggedQuery,
        getMediaIdentityQueryColumns(mediaTableDetail),
        skippedMediaKeys
      );

      if (!currentRow) {
        workflow.allRemainingSkipped =
          workflow.status.remainingCount > 0 && Array.isArray(skippedMediaKeys) && skippedMediaKeys.length > 0;
        workflow.ready =
          Boolean(selectedMapping) &&
          !issues.some((issue) => ["mapping", "tagging"].includes(issue.scope));
        return workflow;
      }

      const mediaTableRow = this.loadMediaTableRow(db, mediaTableDetail, currentRow) ?? currentRow;
      const previewMeta = this.buildPreviewMeta(mediaTableRow[config.pathColumn], connection);
      const existingTagKeys = selectedMapping
        ? this.loadExistingTagKeys(db, currentRow, selectedMapping, tagOptions)
        : [];

      workflow.currentItem = {
        key: buildKeyFromRow(currentRow, getMediaIdentityQueryColumns(mediaTableDetail)),
        identity: buildMediaRowIdentity(mediaTableDetail, mediaTableRow),
        path: mediaTableRow[config.pathColumn],
        previewUrl: previewMeta.previewUrl,
        previewKind: previewMeta.previewKind,
        resolvedPath: previewMeta.resolvedPath,
        existsOnDisk: previewMeta.existsOnDisk,
        row: serializeRow(mediaTableRow),
        existingTagKeys,
      };
      workflow.ready =
        Boolean(selectedMapping) &&
        !issues.some((issue) => issue.severity === "alert" && ["mapping", "tagging"].includes(issue.scope));
      return workflow;
    } catch (error) {
      issues.push(
        buildIssue(
          "tagging",
          "CURRENT_MEDIA_QUERY_FAILED",
          `Current media item could not be loaded: ${error.message}`
        )
      );
      return workflow;
    }
  }

  loadCurrentMediaRow(db, untaggedQuery, identityColumns, skippedMediaKeys = []) {
    const exclusion = buildExcludedKeyClause(identityColumns, skippedMediaKeys);
    const sqlParts = [`SELECT * FROM (${buildWrappedQuery(untaggedQuery)}) AS media_tagging_source`];

    if (exclusion.sql) {
      sqlParts.push(`WHERE NOT (${exclusion.sql})`);
    }

    sqlParts.push("LIMIT 1");

    return db.prepare(sqlParts.join(" ")).get(...exclusion.params) ?? null;
  }

  loadMediaTableRow(db, mediaTableDetail, currentRow) {
    const identityColumns = getMediaIdentityQueryColumns(mediaTableDetail);
    const identityValues = identityColumns.map((column) => currentRow?.[column] ?? null);
    const whereClause = buildKeyWhereClause(identityColumns, identityValues);
    const selectionPrefix =
      mediaTableDetail.identityStrategy?.type === "rowid"
        ? `SELECT rowid AS ${quoteIdentifier(MEDIA_ROWID_ALIAS)}, *`
        : "SELECT *";

    return (
      db
        .prepare(
          `${selectionPrefix} FROM ${quoteIdentifier(mediaTableDetail.name)} WHERE ${whereClause.sql} LIMIT 1`
        )
        .get(...whereClause.params) ?? null
    );
  }

  loadExistingTagKeys(db, currentRow, selectedMapping, tagOptions) {
    const mediaWhere = selectedMapping.mediaForeignKey.mappings
      .map((mapping) => `${quoteIdentifier(mapping.from)} = ?`)
      .join(" AND ");
    const tagSelection = selectedMapping.tagForeignKey.mappings
      .map((mapping) => `${quoteIdentifier(mapping.from)} AS ${quoteIdentifier(mapping.to)}`)
      .join(", ");
    const rows = db
      .prepare(
        `SELECT ${tagSelection} FROM ${quoteIdentifier(selectedMapping.tableName)} WHERE ${mediaWhere}`
      )
      .all(
        selectedMapping.mediaForeignKey.mappings.map((mapping) => currentRow[mapping.to] ?? null)
      );
    const knownTagKeys = new Set(tagOptions.map((option) => option.key));

    return rows
      .map((row) =>
        buildKeyFromRow(
          row,
          selectedMapping.tagForeignKey.mappings.map((mapping) => mapping.to)
        )
      )
      .filter((key) => knownTagKeys.has(key));
  }

  buildPreviewMeta(rawPath, connection) {
    const normalizedPath = String(rawPath ?? "").trim();

    if (!normalizedPath) {
      return {
        previewKind: "unknown",
        previewUrl: null,
        resolvedPath: null,
        existsOnDisk: false,
      };
    }

    if (/^https?:\/\//i.test(normalizedPath) || /^data:/i.test(normalizedPath)) {
      return {
        previewKind: inferPreviewKind(normalizedPath),
        previewUrl: normalizedPath,
        resolvedPath: null,
        existsOnDisk: true,
      };
    }

    const resolvedPath = this.resolveMediaFilePath(normalizedPath, connection);

    return {
      previewKind: inferPreviewKind(normalizedPath),
      previewUrl: `/api/media-tagging/media-file?path=${encodeURIComponent(normalizedPath)}`,
      resolvedPath,
      existsOnDisk: Boolean(resolvedPath && fs.existsSync(resolvedPath)),
    };
  }

  resolveMediaFilePath(rawPath, connection = this.getActiveConnection()) {
    const normalizedPath = String(rawPath ?? "").trim();

    if (!normalizedPath) {
      return null;
    }

    if (/^file:\/\//i.test(normalizedPath)) {
      return fileURLToPath(normalizedPath);
    }

    if (path.isAbsolute(normalizedPath) || path.win32.isAbsolute(normalizedPath)) {
      return normalizedPath;
    }

    const basePath = connection?.path ? path.dirname(connection.path) : process.cwd();
    return path.resolve(basePath, normalizedPath);
  }

  createTag(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const tableCatalog = getTableCatalog(db);
    const config = normalizeMediaTaggingConfig(payload.config ?? {});
    const tagTableDetail = findTableDetail(tableCatalog, config.tagTable);

    if (!tagTableDetail) {
      throw new ValidationError("Choose a valid tag table before creating tags.");
    }

    const insertColumns = getVisibleColumns(tagTableDetail).filter((column) => column.primaryKeyPosition === 0);
    const parentTagFeature = getParentTagFeatureColumns(tagTableDetail);
    const singleIdentityColumn = getSingleTagIdentityColumn(tagTableDetail);
    const requiredIssues = getRequiredInsertColumns(
      tagTableDetail,
      insertColumns.map((column) => column.name)
    );

    if (requiredIssues.length) {
      throw new ValidationError(
        `Tag table "${tagTableDetail.name}" requires additional mandatory columns: ${requiredIssues
          .map((column) => column.name)
          .join(", ")}.`
      );
    }

    const normalizedValues = this.normalizeInsertValues(insertColumns, payload.values ?? {});
    const tagLabelColumns = new Set(getTagLabelColumns(tagTableDetail));

    for (const columnName of tagLabelColumns) {
      if (typeof normalizedValues[columnName] === "string") {
        normalizedValues[columnName] = normalizedValues[columnName].trim().toLowerCase();
      }
    }

    if (parentTagFeature) {
      const parentFlagColumnName = parentTagFeature.flagColumn.name;
      const parentIdColumnName = parentTagFeature.parentIdColumn.name;
      const isParentTag = normalizedValues[parentFlagColumnName] === 1;

      if (isParentTag) {
        delete normalizedValues[parentIdColumnName];
      } else if (Object.prototype.hasOwnProperty.call(normalizedValues, parentIdColumnName)) {
        if (!singleIdentityColumn) {
          throw new ValidationError(
            `Tag table "${tagTableDetail.name}" must expose a single-column primary key to support parent tags.`
          );
        }

        const parentTag = db
          .prepare(
            `SELECT * FROM ${quoteIdentifier(tagTableDetail.name)} WHERE ${quoteIdentifier(
              singleIdentityColumn
            )} = ? LIMIT 1`
          )
          .get(normalizedValues[parentIdColumnName]);

        if (!parentTag) {
          throw new ValidationError("The selected parent tag no longer exists.");
        }

        if (!parentTag[parentFlagColumnName]) {
          throw new ValidationError("The selected parent tag must itself be marked as a parent tag.");
        }
      }
    }

    const providedColumns = insertColumns.filter((column) =>
      Object.prototype.hasOwnProperty.call(normalizedValues, column.name)
    );

    if (!providedColumns.length) {
      throw new ValidationError("Enter at least one tag value before saving.");
    }

    const sql = `
      INSERT INTO ${quoteIdentifier(tagTableDetail.name)} (${providedColumns
        .map((column) => quoteIdentifier(column.name))
        .join(", ")})
      VALUES (${providedColumns.map(() => "?").join(", ")})
    `;

    const providedColumnNames = providedColumns.map((column) => column.name);
    const insertTag = db.transaction(() => {
      const result = db
        .prepare(sql)
        .run(providedColumns.map((column) => normalizedValues[column.name]));
      const implicitPrimaryKey = getVisibleColumns(tagTableDetail).find((column) =>
        canBackfillPrimaryKeyFromRowId(tagTableDetail, column)
      );

      // Rowid tables can accept an omitted single-column PK. Backfill it from rowid so
      // the tag still ends up with a stable key for selection and mapping.
      if (implicitPrimaryKey && !providedColumnNames.includes(implicitPrimaryKey.name)) {
        db.prepare(
          `
            UPDATE ${quoteIdentifier(tagTableDetail.name)}
            SET ${quoteIdentifier(implicitPrimaryKey.name)} = ?
            WHERE rowid = ?
              AND ${quoteIdentifier(implicitPrimaryKey.name)} IS NULL
          `
        ).run(result.lastInsertRowid, result.lastInsertRowid);
      }
    });

    try {
      insertTag();
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  deleteTag(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const tableCatalog = getTableCatalog(db);
    const config = normalizeMediaTaggingConfig(payload.config ?? {});
    const tagTableDetail = findTableDetail(tableCatalog, config.tagTable);
    const { candidates } = findMappingMatches(tableCatalog, config.mediaTable, config.tagTable);
    const selectedMapping = inferSelectedMapping(candidates, config.mappingTable).selectedCandidate;

    if (!tagTableDetail) {
      throw new ValidationError("Choose a valid tag table before removing tags.");
    }

    const keyColumns = selectedMapping
      ? selectedMapping.tagForeignKey.mappings.map((mapping) => mapping.to)
      : getTagIdentityQueryColumns(tagTableDetail);

    if (!keyColumns.length) {
      throw new ValidationError(
        `Tag table "${tagTableDetail.name}" does not expose a stable key for deletion.`
      );
    }

    const keyValues = decodeKey(payload.tagKey, keyColumns.length);
    const deleteTagTransaction = db.transaction(() => {
      if (selectedMapping) {
        const mappingColumns = selectedMapping.tagForeignKey.mappings.map((mapping) => mapping.from);
        const mappingWhere = buildKeyWhereClause(mappingColumns, keyValues);

        db.prepare(
          `DELETE FROM ${quoteIdentifier(selectedMapping.tableName)} WHERE ${mappingWhere.sql}`
        ).run(mappingWhere.params);
      }

      const tagWhere = buildKeyWhereClause(keyColumns, keyValues);
      const result = db
        .prepare(`DELETE FROM ${quoteIdentifier(tagTableDetail.name)} WHERE ${tagWhere.sql}`)
        .run(tagWhere.params);

      if (!result.changes) {
        throw new NotFoundError("The selected tag could not be found anymore.");
      }
    });

    try {
      deleteTagTransaction();
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  normalizeInsertValues(columns = [], values = {}) {
    return Object.fromEntries(
      columns.flatMap((column) => {
        const rawValue = values?.[column.name];

        if (rawValue === undefined || rawValue === null || rawValue === "") {
          if (column.notNull && column.defaultValue === null) {
            throw new ValidationError(`Field "${column.name}" is required.`);
          }

          return [];
        }

        const inputKind = getColumnInputKind(column);

        if (inputKind === "checkbox") {
          return [[column.name, rawValue ? 1 : 0]];
        }

        if (inputKind === "number") {
          const numericValue = Number(rawValue);

          if (!Number.isFinite(numericValue)) {
            throw new ValidationError(`Field "${column.name}" must be numeric.`);
          }

          return [[column.name, numericValue]];
        }

        return [[column.name, String(rawValue)]];
      })
    );
  }

  applyTagging(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const connection = this.getActiveConnection();
    const tableCatalog = getTableCatalog(db);
    const config = normalizeMediaTaggingConfig(payload.config ?? {});
    const mediaTableDetail = findTableDetail(tableCatalog, config.mediaTable);
    const { candidates } = findMappingMatches(tableCatalog, config.mediaTable, config.tagTable);
    const selectedMapping = inferSelectedMapping(candidates, config.mappingTable).selectedCandidate;

    if (!mediaTableDetail || !selectedMapping) {
      throw new ValidationError("Media tagging configuration is incomplete.");
    }

    const viewState = this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
    const currentItem = viewState.workflow?.currentItem ?? null;

    if (!currentItem) {
      throw new ValidationError("No current media item is available for tagging.");
    }

    if (payload.currentItemKey && payload.currentItemKey !== currentItem.key) {
      throw new ValidationError("The current media item changed. Refresh the tagging view.");
    }

    const currentRow = this.loadCurrentMediaRow(
      db,
      config.untaggedQuery,
      getMediaIdentityQueryColumns(mediaTableDetail),
      payload.skippedMediaKeys ?? []
    );

    if (!currentRow) {
      throw new ValidationError("No current media item is available for tagging.");
    }

    const selectedTagKeys = Array.isArray(payload.selectedTagKeys)
      ? payload.selectedTagKeys.filter(Boolean)
      : [];
    const selectedTagOptions = viewState.tags.filter((tag) => selectedTagKeys.includes(tag.key));

    const applyTransaction = db.transaction(() => {
      selectedTagOptions.forEach((tagOption) => {
        const tagValues = decodeKey(
          tagOption.key,
          selectedMapping.tagForeignKey.mappings.length
        );
        const mappingPayload = {};

        selectedMapping.mediaForeignKey.mappings.forEach((mapping) => {
          mappingPayload[mapping.from] = currentRow[mapping.to] ?? null;
        });
        selectedMapping.tagForeignKey.mappings.forEach((mapping, index) => {
          mappingPayload[mapping.from] = tagValues[index] ?? null;
        });

        if (!this.mappingExists(db, selectedMapping.tableName, mappingPayload)) {
          const columns = Object.keys(mappingPayload);
          const insertSql = `
            INSERT INTO ${quoteIdentifier(selectedMapping.tableName)} (${columns
              .map((column) => quoteIdentifier(column))
              .join(", ")})
            VALUES (${columns.map(() => "?").join(", ")})
          `;

          db.prepare(insertSql).run(columns.map((column) => mappingPayload[column]));
        }
      });

      const shouldMarkTagged = payload.markTagged !== false;

      if (shouldMarkTagged) {
        this.markMediaRowTagged(db, mediaTableDetail, config.taggedColumn, currentRow);
      }
    });

    try {
      applyTransaction();
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  skipCurrentMedia(payload = {}) {
    this.connectionManager.assertWritable();

    const db = this.connectionManager.getActiveDatabase();
    const tableCatalog = getTableCatalog(db);
    const config = normalizeMediaTaggingConfig(payload.config ?? {});
    const mediaTableDetail = findTableDetail(tableCatalog, config.mediaTable);

    if (!mediaTableDetail || !config.taggedColumn) {
      throw new ValidationError("Media tagging configuration is incomplete.");
    }

    const viewState = this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
    const currentItem = viewState.workflow?.currentItem ?? null;

    if (!currentItem) {
      throw new ValidationError("No current media item is available for tagging.");
    }

    if (payload.currentItemKey && payload.currentItemKey !== currentItem.key) {
      throw new ValidationError("The current media item changed. Refresh the tagging view.");
    }

    const currentRow = this.loadCurrentMediaRow(
      db,
      config.untaggedQuery,
      getMediaIdentityQueryColumns(mediaTableDetail),
      payload.skippedMediaKeys ?? []
    );

    if (!currentRow) {
      throw new ValidationError("No current media item is available for tagging.");
    }

    try {
      this.markMediaRowTagged(db, mediaTableDetail, config.taggedColumn, currentRow);
    } catch (error) {
      throw mapSqliteError(error);
    }

    return this.getViewState({
      config,
      skippedMediaKeys: payload.skippedMediaKeys ?? [],
    });
  }

  mappingExists(db, mappingTableName, mappingPayload) {
    const columns = Object.keys(mappingPayload);

    if (!columns.length) {
      return false;
    }

    const whereClause = columns.map((column) => `${quoteIdentifier(column)} = ?`).join(" AND ");
    const row = db
      .prepare(
        `SELECT 1 AS exists_flag FROM ${quoteIdentifier(mappingTableName)} WHERE ${whereClause} LIMIT 1`
      )
      .get(columns.map((column) => mappingPayload[column]));

    return Boolean(row?.exists_flag);
  }

  markMediaRowTagged(db, mediaTableDetail, taggedColumn, currentRow) {
    const identity = mediaTableDetail.identityStrategy ?? { type: "none", columns: [] };

    if (identity.type === "primaryKey" && identity.columns.length) {
      const whereClause = identity.columns
        .map((column) => `${quoteIdentifier(column)} = ?`)
        .join(" AND ");
      const values = identity.columns.map((column) => currentRow[column] ?? null);

      db.prepare(
        `UPDATE ${quoteIdentifier(mediaTableDetail.name)} SET ${quoteIdentifier(
          taggedColumn
        )} = 1 WHERE ${whereClause}`
      ).run(values);
      return;
    }

    if (identity.type === "rowid") {
      const rowIdValue = currentRow[MEDIA_ROWID_ALIAS];

      if (rowIdValue === null || rowIdValue === undefined) {
        throw new ValidationError(
          `Current media row is missing "${MEDIA_ROWID_ALIAS}" and cannot be updated.`
        );
      }

      db.prepare(
        `UPDATE ${quoteIdentifier(mediaTableDetail.name)} SET ${quoteIdentifier(
          taggedColumn
        )} = 1 WHERE rowid = ?`
      ).run(rowIdValue);
      return;
    }

    throw new ValidationError(
      `Media table "${mediaTableDetail.name}" cannot be updated safely because it has no identity column.`
    );
  }
}

module.exports = {
  MediaTaggingService,
};
