const { quoteIdentifier } = require("../../utils/identifier");
const { getTableDetail } = require("./introspection");

/**
 * @typedef {"info" | "warning" | "critical"} TableAdvisorSeverity
 * @typedef {"schema" | "constraints" | "performance" | "data-quality" | "documentation"} TableAdvisorCategory
 * @typedef {"low" | "medium" | "high"} TableAdvisorRisk
 *
 * @typedef {Object} ColumnProfile
 * @property {string} name
 * @property {string} type
 * @property {boolean} notNull
 * @property {string | null} defaultValue
 * @property {boolean} primaryKey
 * @property {number} nullCount
 * @property {number} emptyStringCount
 * @property {number} distinctCount
 * @property {number} totalCount
 * @property {{ value: string | number | null, count: number }[]} topValues
 * @property {string | number | null} [minValue]
 * @property {string | number | null} [maxValue]
 *
 * @typedef {Object} TableAdvisorIssue
 * @property {string} id
 * @property {TableAdvisorSeverity} severity
 * @property {TableAdvisorCategory} category
 * @property {string} title
 * @property {string} explanation
 * @property {string} [evidence]
 * @property {string} recommendation
 * @property {string} [sql]
 * @property {boolean} fixAvailable
 * @property {string} [fixUnavailableReason]
 * @property {{ tables: string[], columns: string[], indexes: string[] }} affectedObjects
 * @property {string[]} warnings
 * @property {boolean} backupRecommended
 * @property {boolean} destructive
 * @property {TableAdvisorRisk} risk
 *
 * @typedef {Object} TableAdvisorResult
 * @property {string} tableName
 * @property {number} score
 * @property {TableAdvisorIssue[]} issues
 * @property {string} analyzedAt
 * @property {number} [issueCount]
 * @property {number} [rowCount]
 * @property {ColumnProfile[]} [columnProfiles]
 * @property {{ columnCount: number, indexCount: number, foreignKeyCount: number }} [table]
 */

const LIKELY_UNIQUE_COLUMNS = new Set([
  "email",
  "slug",
  "uuid",
  "username",
  "handle",
  "external_id",
  "externalid",
]);

const ENUM_LIKE_COLUMNS = new Set([
  "status",
  "state",
  "type",
  "kind",
  "category",
]);

const GENERIC_COLUMN_NAMES = new Set([
  "data",
  "value",
  "text",
  "temp",
  "misc",
  "payload",
  "json",
  "field1",
  "field2",
]);

const CREATED_AT_COLUMNS = new Set(["created_at", "createdat", "inserted_at", "created"]);
const UPDATED_AT_COLUMNS = new Set(["updated_at", "updatedat"]);
const LARGE_TABLE_DUPLICATE_CHECK_LIMIT = 100000;
const QUERY_ORIGIN = "Generated by Advisor";

function normalizeColumnName(name) {
  return String(name ?? "").trim().toLowerCase();
}

function normalizeIdentifierPart(value) {
  return String(value ?? "")
    .trim()
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase() || "column";
}

function getColumnSqlType(column) {
  return column.declaredType || column.affinity || "ANY";
}

function getProfileType(column) {
  return column.declaredType || column.affinity || "ANY";
}

function isPrimaryKey(column) {
  return Number(column.primaryKeyPosition ?? 0) > 0;
}

function isTextLikeColumn(column) {
  const type = getColumnSqlType(column).toUpperCase();
  return column.affinity === "TEXT" || /CHAR|CLOB|TEXT|VARCHAR|STRING|JSON/i.test(type);
}

function isNumericLikeColumn(column) {
  return ["INTEGER", "REAL", "NUMERIC"].includes(column.affinity);
}

function isDateLikeColumn(column) {
  const name = normalizeColumnName(column.name);
  const type = getColumnSqlType(column).toUpperCase();

  return (
    /DATE|TIME/i.test(type) ||
    name.endsWith("_at") ||
    name.endsWith("at") ||
    name.includes("date") ||
    name.includes("time")
  );
}

function isLikelyUniqueColumn(column) {
  return LIKELY_UNIQUE_COLUMNS.has(normalizeColumnName(column.name));
}

function isEnumLikeColumn(column) {
  return ENUM_LIKE_COLUMNS.has(normalizeColumnName(column.name));
}

function isGenericColumnName(column) {
  return GENERIC_COLUMN_NAMES.has(normalizeColumnName(column.name));
}

function isCreatedAtColumn(column) {
  return CREATED_AT_COLUMNS.has(normalizeColumnName(column.name));
}

function isUpdatedAtColumn(column) {
  return UPDATED_AT_COLUMNS.has(normalizeColumnName(column.name));
}

function isForeignKeyLikeColumn(column) {
  const name = String(column.name ?? "");

  return !isPrimaryKey(column) && (name.endsWith("_id") || /Id$/.test(name));
}

function hasCurrentTimestampDefault(defaultValue) {
  return /\bCURRENT_TIMESTAMP\b|\bCURRENT_DATE\b|\bdatetime\s*\(/i.test(String(defaultValue ?? ""));
}

function hasExactUniqueIndex(tableDetail, columnName) {
  return (tableDetail.indexes ?? []).some((index) => {
    if (!index.unique || index.partial) {
      return false;
    }

    const columns = (index.columns ?? [])
      .filter((column) => column.name)
      .map((column) => column.name);

    return columns.length === 1 && columns[0] === columnName;
  });
}

function hasIndexOnColumn(tableDetail, columnName) {
  return (tableDetail.indexes ?? []).some((index) => {
    const columns = (index.columns ?? [])
      .filter((column) => column.name)
      .map((column) => column.name);

    return columns[0] === columnName;
  });
}

function hasForeignKeyOnColumn(tableDetail, columnName) {
  return (tableDetail.foreignKeys ?? []).some((foreignKey) =>
    (foreignKey.mappings ?? []).some((mapping) => mapping.from === columnName)
  );
}

function countRows(db, tableName, whereClause = "", params = []) {
  const sql = [
    "SELECT COUNT(*) AS count FROM",
    quoteIdentifier(tableName),
    whereClause ? `WHERE ${whereClause}` : "",
  ]
    .filter(Boolean)
    .join(" ");

  return Number(db.prepare(sql).get(...params)?.count ?? 0);
}

function getDistinctCount(db, tableName, columnName) {
  const sql = [
    "SELECT COUNT(DISTINCT",
    quoteIdentifier(columnName),
    ") AS count FROM",
    quoteIdentifier(tableName),
  ].join(" ");

  return Number(db.prepare(sql).get()?.count ?? 0);
}

function normalizeProfileValue(value) {
  if (value === null || value === undefined) {
    return null;
  }

  if (typeof value === "number" || typeof value === "string") {
    return value;
  }

  if (Buffer.isBuffer(value)) {
    return `BLOB ${value.length} bytes`;
  }

  return String(value);
}

function getTopValues(db, tableName, columnName) {
  const columnSql = quoteIdentifier(columnName);
  const sql = [
    "SELECT",
    columnSql,
    "AS value, COUNT(*) AS count FROM",
    quoteIdentifier(tableName),
    "GROUP BY",
    columnSql,
    "ORDER BY count DESC LIMIT 10",
  ].join(" ");

  return db.prepare(sql).all().map((row) => ({
    value: normalizeProfileValue(row.value),
    count: Number(row.count ?? 0),
  }));
}

function getMinMax(db, tableName, columnName) {
  const columnSql = quoteIdentifier(columnName);
  const row = db
    .prepare(
      [
        "SELECT MIN(",
        columnSql,
        ") AS minValue, MAX(",
        columnSql,
        ") AS maxValue FROM",
        quoteIdentifier(tableName),
      ].join(" ")
    )
    .get();

  return {
    minValue: normalizeProfileValue(row?.minValue),
    maxValue: normalizeProfileValue(row?.maxValue),
  };
}

function getDuplicateValues(db, tableName, columnName) {
  const columnSql = quoteIdentifier(columnName);
  const sql = [
    "SELECT",
    columnSql,
    "AS value, COUNT(*) AS count FROM",
    quoteIdentifier(tableName),
    "WHERE",
    columnSql,
    "IS NOT NULL",
    "GROUP BY",
    columnSql,
    "HAVING COUNT(*) > 1",
    "ORDER BY count DESC LIMIT 10",
  ].join(" ");

  return db.prepare(sql).all().map((row) => ({
    value: normalizeProfileValue(row.value),
    count: Number(row.count ?? 0),
  }));
}

function profileColumn(db, tableDetail, column) {
  const tableName = tableDetail.name;
  const columnSql = quoteIdentifier(column.name);
  const profile = {
    name: column.name,
    type: getProfileType(column),
    affinity: column.affinity,
    notNull: Boolean(column.notNull),
    defaultValue: column.defaultValue ?? null,
    primaryKey: isPrimaryKey(column),
    nullCount: countRows(db, tableName, `${columnSql} IS NULL`),
    emptyStringCount: 0,
    distinctCount: getDistinctCount(db, tableName, column.name),
    totalCount: Number(tableDetail.rowCount ?? 0),
    topValues: getTopValues(db, tableName, column.name),
    duplicateValues: [],
  };

  if (isTextLikeColumn(column)) {
    profile.emptyStringCount = countRows(
      db,
      tableName,
      `${columnSql} IS NOT NULL AND TRIM(CAST(${columnSql} AS TEXT)) = ''`
    );
  }

  if (isNumericLikeColumn(column) || isDateLikeColumn(column)) {
    const range = getMinMax(db, tableName, column.name);
    profile.minValue = range.minValue;
    profile.maxValue = range.maxValue;
  }

  if (
    isLikelyUniqueColumn(column) &&
    Number(tableDetail.rowCount ?? 0) <= LARGE_TABLE_DUPLICATE_CHECK_LIMIT
  ) {
    profile.duplicateValues = getDuplicateValues(db, tableName, column.name);
  }

  return profile;
}

function profileTable(db, tableDetail) {
  return (tableDetail.columns ?? [])
    .filter((column) => column.visible && !column.generated)
    .map((column) => profileColumn(db, tableDetail, column));
}

function formatEvidenceValue(value) {
  if (value === null) {
    return "NULL";
  }

  if (value === undefined) {
    return "undefined";
  }

  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  return String(value);
}

function formatTopValueList(values = []) {
  return values
    .slice(0, 5)
    .map((item) => `${formatEvidenceValue(item.value)} (${item.count})`)
    .join(", ");
}

function buildIndexName(tableName, columnName, suffix = "") {
  return normalizeIdentifierPart(["idx", tableName, columnName, suffix].filter(Boolean).join("_"));
}

function buildAvailableIndexName(tableDetail, columnName, unique = false) {
  const baseName = buildIndexName(tableDetail.name, columnName, unique ? "unique" : "");
  const existingNames = new Set(
    [...(tableDetail.schemaObjectNames ?? []), ...(tableDetail.indexes ?? []).map((index) => index.name)]
      .map((name) => String(name ?? "").toLowerCase())
  );

  if (!existingNames.has(baseName.toLowerCase())) {
    return baseName;
  }

  let suffix = 2;
  while (existingNames.has(`${baseName}_${suffix}`.toLowerCase())) {
    suffix += 1;
  }

  return `${baseName}_${suffix}`;
}

function buildTransactionSql(statement) {
  return ["BEGIN TRANSACTION;", "", statement, "", "COMMIT;"].join("\n");
}

function buildCreateIndexSql({ tableName, columnName, indexName, unique = false }) {
  const createKeyword = unique ? "CREATE UNIQUE INDEX" : "CREATE INDEX";

  return buildTransactionSql(
    `${createKeyword} IF NOT EXISTS ${quoteIdentifier(indexName)}\nON ${quoteIdentifier(tableName)} (${quoteIdentifier(columnName)});`
  );
}

function buildEmptyStringCleanupSql(tableName, columnName) {
  const columnSql = quoteIdentifier(columnName);

  return buildTransactionSql(
    `UPDATE ${quoteIdentifier(tableName)}\nSET ${columnSql} = NULL\nWHERE TRIM(CAST(${columnSql} AS TEXT)) = '';`
  );
}

function buildUpdatedAtTriggerSql(tableDetail, columnName) {
  if ((tableDetail.triggers ?? []).length > 0) {
    return null;
  }

  const baseTriggerName = normalizeIdentifierPart(["trg", tableDetail.name, columnName].join("_"));
  const existingNames = new Set(
    (tableDetail.schemaObjectNames ?? []).map((name) => String(name ?? "").toLowerCase())
  );
  let triggerName = baseTriggerName;
  let suffix = 2;

  while (existingNames.has(triggerName.toLowerCase())) {
    triggerName = `${baseTriggerName}_${suffix}`;
    suffix += 1;
  }
  const columnSql = quoteIdentifier(columnName);
  let whereClause = "";

  if (tableDetail.identityStrategy?.type === "primaryKey") {
    whereClause = tableDetail.identityStrategy.columns
      .map((primaryKeyColumn) => {
        const quoted = quoteIdentifier(primaryKeyColumn);
        return `${quoted} IS NEW.${quoted}`;
      })
      .join(" AND ");
  } else if (tableDetail.identityStrategy?.type === "rowid") {
    whereClause = "rowid = NEW.rowid";
  }

  if (!whereClause) {
    return null;
  }

  return buildTransactionSql([
    `CREATE TRIGGER IF NOT EXISTS ${quoteIdentifier(triggerName)}`,
    `AFTER UPDATE ON ${quoteIdentifier(tableDetail.name)}`,
    "FOR EACH ROW",
    `WHEN OLD.${columnSql} IS NEW.${columnSql}`,
    `  AND NEW.${columnSql} IS NOT CURRENT_TIMESTAMP`,
    "BEGIN",
    `  UPDATE ${quoteIdentifier(tableDetail.name)}`,
    `  SET ${columnSql} = CURRENT_TIMESTAMP`,
    `  WHERE ${whereClause};`,
    "END;",
  ].join("\n"));
}

function makeIssue(issue) {
  return { ...issue };
}

function getIssueTargetColumn(tableDetail, issue) {
  const candidate = String(issue.id ?? "").split(":")[1] ?? "";

  return (tableDetail.columns ?? []).some((column) => column.name === candidate) ? candidate : null;
}

function getFixWarnings(sql) {
  const normalizedSql = String(sql ?? "").toUpperCase();

  if (normalizedSql.includes("CREATE UNIQUE INDEX")) {
    return [
      "This query changes the database schema.",
      "Index creation can take a long time on large tables and temporarily use additional storage.",
      "The database file can grow, and existing applications may use a different query plan afterwards.",
      "The UNIQUE index will fail if conflicting values are written after this analysis.",
      "Creating a backup before execution is recommended.",
    ];
  }

  if (normalizedSql.includes("CREATE INDEX")) {
    return [
      "This query changes the database schema.",
      "Index creation can take a long time on large tables and temporarily use additional storage.",
      "The database file can grow, and existing applications may use a different query plan afterwards.",
      "Creating a backup before execution is recommended.",
    ];
  }

  if (normalizedSql.includes("CREATE TRIGGER")) {
    return [
      "This query changes the database schema.",
      "The trigger changes the behavior and cost of future UPDATE statements on this table.",
      "Existing applications that maintain this column themselves may be affected.",
      "Creating a backup before execution is recommended.",
    ];
  }

  if (/\b(?:UPDATE|DELETE|DROP|ALTER\s+TABLE)\b/.test(normalizedSql)) {
    return [
      "This query changes existing data or schema and cannot automatically restore the previous values.",
      "The operation can take a long time on large tables and may temporarily use additional storage.",
      "Existing queries or applications may be affected by the changed values.",
      "Creating a backup before execution is strongly recommended.",
    ];
  }

  return [];
}

function finalizeIssue(tableDetail, issue) {
  const targetColumn = getIssueTargetColumn(tableDetail, issue);
  const originalSql = String(issue.sql ?? "").trim();
  const protectedTable =
    Boolean(tableDetail.isVirtual) ||
    Boolean(tableDetail.isShadow) ||
    String(tableDetail.name ?? "").toLowerCase().startsWith("sqlite_");
  const sql = protectedTable ? "" : originalSql;
  const firstFixStatement = sql.replace(/^BEGIN\s+TRANSACTION\s*;/i, "").trim();
  const destructive = /^(?:UPDATE|DELETE|DROP\s+TABLE|ALTER\s+TABLE)\b/i.test(firstFixStatement);
  const indexes = [];

  const indexMatch = sql.match(
    /\bCREATE\s+(?:UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\s+"((?:[^"]|"")+)"/i
  );
  if (indexMatch) {
    indexes.push(indexMatch[1].replaceAll('""', '"'));
  }

  let fixUnavailableReason = issue.fixUnavailableReason;

  if (protectedTable && originalSql) {
    fixUnavailableReason = tableDetail.isShadow
      ? "Shadow tables are managed by their owning virtual table and must not be changed directly."
      : tableDetail.isVirtual
        ? "This virtual table is managed by its SQLite module; a generic table fix is not technically safe."
        : "Internal SQLite tables must not be changed by the Advisor.";
  } else if (!sql && !fixUnavailableReason) {
    fixUnavailableReason = "No complete, context-safe SQL fix can be generated for this issue.";
  }

  return {
    ...issue,
    ...(sql ? { sql } : { sql: undefined }),
    ...(sql ? {} : { fixUnavailableReason }),
    severity: destructive ? "critical" : issue.severity,
    risk: destructive ? "high" : issue.risk,
    fixAvailable: Boolean(sql),
    affectedObjects: {
      tables: [tableDetail.name],
      columns: targetColumn ? [targetColumn] : [],
      indexes,
    },
    warnings: getFixWarnings(sql),
    backupRecommended: Boolean(sql),
    destructive,
    ...(sql ? { queryOrigin: QUERY_ORIGIN } : {}),
  };
}

function getProfile(columnProfiles, columnName) {
  return columnProfiles.find((profile) => profile.name === columnName);
}

function generateMissingPrimaryKeyIssue(tableDetail) {
  const hasPrimaryKey = (tableDetail.columns ?? []).some((column) => isPrimaryKey(column));

  if (hasPrimaryKey) {
    return null;
  }

  return makeIssue({
    id: "schema:missing-primary-key",
    severity: "critical",
    category: "schema",
    title: "Table has no primary key",
    explanation:
      "Rows in this table are not uniquely identifiable. This can make updates, relations, exports and synchronization harder.",
    evidence: `Table ${tableDetail.name} has 0 primary key columns.`,
    recommendation: "Add an INTEGER PRIMARY KEY column if this table stores entities.",
    fixUnavailableReason:
      "A safe fix needs a chosen key name and values plus a complete table rebuild; the Advisor must not invent them.",
    risk: "high",
  });
}

function generateColumnIssues(tableDetail, columnProfiles) {
  const issues = [];
  const rowCount = Number(tableDetail.rowCount ?? 0);

  (tableDetail.columns ?? [])
    .filter((column) => column.visible && !column.generated)
    .forEach((column) => {
      const profile = getProfile(columnProfiles, column.name);

      if (!profile) {
        return;
      }

      const nonNullCount = Math.max(0, rowCount - profile.nullCount);
      const nullRatio = rowCount > 0 ? profile.nullCount / rowCount : 0;
      const duplicateValues = profile.duplicateValues ?? [];

      if (isCreatedAtColumn(column) && !hasCurrentTimestampDefault(column.defaultValue)) {
        issues.push(
          makeIssue({
            id: `schema:${column.name}:missing-created-default`,
            severity: "warning",
            category: "schema",
            title: `${column.name} has no timestamp default`,
            explanation:
              "Creation timestamp columns are more reliable when SQLite assigns the value consistently at insert time.",
            evidence: `${column.name} default is ${column.defaultValue ?? "NULL"}.`,
            recommendation: "Use DEFAULT CURRENT_TIMESTAMP when rebuilding or adding this column.",
            fixUnavailableReason:
              "SQLite cannot change an existing column default directly. A complete rebuild must preserve every constraint, index, trigger, and foreign key.",
            risk: "medium",
          })
        );
      }

      if (isUpdatedAtColumn(column)) {
        const triggerSql = buildUpdatedAtTriggerSql(tableDetail, column.name);
        const triggerUnavailableReason = (tableDetail.triggers ?? []).length
          ? "Existing triggers can interact with timestamp maintenance, so the Advisor will not add another trigger automatically."
          : "This table has no stable row identity that a safe maintenance trigger can target.";

        issues.push(
          makeIssue({
            id: `schema:${column.name}:updated-at-maintenance`,
            severity: "info",
            category: "schema",
            title: `${column.name} needs maintenance logic`,
            explanation:
              "SQLite does not update timestamp columns automatically. Use application logic or a trigger if this column should track changes.",
            evidence: `${column.name} exists on ${tableDetail.name}.`,
            recommendation: "Verify writes always refresh this column before relying on it for recency.",
            ...(triggerSql ? { sql: triggerSql } : { fixUnavailableReason: triggerUnavailableReason }),
            risk: "medium",
          })
        );
      }

      if (isLikelyUniqueColumn(column) && duplicateValues.length) {
        const duplicateRows = duplicateValues.reduce((total, item) => total + Number(item.count ?? 0), 0);
        issues.push(
          makeIssue({
            id: `data-quality:${column.name}:duplicate-values`,
            severity: duplicateRows > Math.max(10, rowCount * 0.05) ? "critical" : "warning",
            category: "data-quality",
            title: `${column.name} contains duplicates`,
            explanation:
              "This column looks like a natural identifier, but duplicate values would make a UNIQUE constraint fail.",
            evidence: `Duplicate examples: ${formatTopValueList(duplicateValues)}.`,
            recommendation: "Resolve duplicate values before adding a UNIQUE index.",
            fixUnavailableReason:
              "Choosing which duplicate value to keep requires application semantics; the Advisor must not invent replacement values.",
            risk: "medium",
          })
        );
      } else if (
        isLikelyUniqueColumn(column) &&
        rowCount > 0 &&
        nonNullCount > 0 &&
        nullRatio <= 0.02 &&
        profile.distinctCount === nonNullCount &&
        !hasExactUniqueIndex(tableDetail, column.name)
      ) {
        issues.push(
          makeIssue({
            id: `constraints:${column.name}:missing-unique-index`,
            severity: "warning",
            category: "constraints",
            title: `${column.name} looks unique but is not enforced`,
            explanation:
              "The sampled profile shows unique non-null values, but no single-column UNIQUE index enforces that expectation.",
            evidence: `${formatTopValueList(profile.topValues)}. Distinct non-null values: ${profile.distinctCount}/${nonNullCount}.`,
            recommendation: "Add a UNIQUE index after verifying the column is meant to be unique.",
            sql: buildCreateIndexSql({
              tableName: tableDetail.name,
              columnName: column.name,
              indexName: buildAvailableIndexName(tableDetail, column.name, true),
              unique: true,
            }),
            risk: "medium",
          })
        );
      }

      if (
        isEnumLikeColumn(column) &&
        rowCount > 0 &&
        profile.distinctCount >= 2 &&
        profile.distinctCount <= 10 &&
        !(column.allowedValues ?? []).length
      ) {
        const values = (profile.topValues ?? [])
          .map((item) => item.value)
          .filter((value) => value !== null && value !== undefined)
          .slice(0, 10);

        if (values.length >= 2) {
          issues.push(
            makeIssue({
              id: `constraints:${column.name}:check-constraint`,
              severity: "info",
              category: "constraints",
              title: `${column.name} has enum-like values`,
              explanation:
                "The column uses a small set of values. A CHECK constraint can document and enforce the allowed set, but SQLite cannot add it to an existing column without a rebuild.",
              evidence: `Observed values: ${formatTopValueList(profile.topValues)}.`,
              recommendation: "Consider a CHECK constraint in the next schema rebuild.",
              fixUnavailableReason:
                "Observed values do not prove the complete allowed set, and adding the constraint requires a full table rebuild.",
              risk: "high",
            })
          );
        }
      }

      if (rowCount > 0 && nullRatio > 0.5) {
        issues.push(
          makeIssue({
            id: `data-quality:${column.name}:mostly-null`,
            severity: "info",
            category: "data-quality",
            title: `${column.name} is mostly NULL`,
            explanation: "Mostly-empty columns can be valid, but they often indicate optional data that should be reviewed.",
            evidence: `${profile.nullCount}/${rowCount} rows are NULL.`,
            recommendation: "Confirm this column is still useful or split optional data into a related table.",
            fixUnavailableReason:
              "The intended meaning of NULL values is unknown, so no safe automatic data or schema change is available.",
            risk: "low",
          })
        );
      }

      if (!column.notNull && !isPrimaryKey(column) && rowCount >= 10 && profile.nullCount === 0) {
        issues.push(
          makeIssue({
            id: `constraints:${column.name}:nullable-required`,
            severity: "info",
            category: "constraints",
            title: `${column.name} is nullable but currently always filled`,
            explanation:
              "The data profile suggests the column may be required even though the schema allows NULL.",
            evidence: `0/${rowCount} rows are NULL.`,
            recommendation: "Consider NOT NULL in a future table rebuild if this is a real requirement.",
            fixUnavailableReason:
              "Current data cannot establish a permanent NOT NULL requirement, and SQLite would require a complete table rebuild.",
            risk: "high",
          })
        );
      }

      if (profile.emptyStringCount > 0) {
        let cleanupUnavailableReason = "";

        if (column.notNull) {
          cleanupUnavailableReason =
            "This column is NOT NULL, so replacing empty strings with NULL would violate the existing constraint.";
        } else if ((tableDetail.checkConstraints ?? []).length > 0) {
          cleanupUnavailableReason =
            "Existing CHECK constraints may reject NULL or depend on this value, so the update cannot be proven safe automatically.";
        } else if ((tableDetail.triggers ?? []).length > 0) {
          cleanupUnavailableReason =
            "The update would execute existing table triggers whose additional effects cannot be explained safely by this fix.";
        }

        issues.push(
          makeIssue({
            id: `data-quality:${column.name}:empty-strings`,
            severity: "warning",
            category: "data-quality",
            title: `${column.name} contains empty strings`,
            explanation:
              "Empty strings and NULL values can represent different states. Mixing both often makes filtering and validation harder.",
            evidence: `${profile.emptyStringCount}/${rowCount} rows are empty strings.`,
            recommendation:
              "Normalize empty strings to NULL or enforce a NOT NULL plus CHECK(length(trim(column)) > 0) rule.",
            ...(!cleanupUnavailableReason
              ? { sql: buildEmptyStringCleanupSql(tableDetail.name, column.name) }
              : { fixUnavailableReason: cleanupUnavailableReason }),
            risk: "medium",
          })
        );
      }

      if (isForeignKeyLikeColumn(column) && !hasForeignKeyOnColumn(tableDetail, column.name)) {
        issues.push(
          makeIssue({
            id: `schema:${column.name}:missing-foreign-key`,
            severity: "warning",
            category: "schema",
            title: `${column.name} looks like a foreign key`,
            explanation:
              "The column name follows an id-reference pattern, but the schema has no FOREIGN KEY constraint for it.",
            evidence: `${column.name} has no foreign_key_list entry.`,
            recommendation: "Add a FOREIGN KEY in a table rebuild if this column references another table.",
            fixUnavailableReason:
              "The referenced table and column cannot be inferred safely from the column name, and SQLite requires a table rebuild.",
            risk: "high",
          })
        );
      }

      if (isForeignKeyLikeColumn(column) && !hasIndexOnColumn(tableDetail, column.name)) {
        issues.push(
          makeIssue({
            id: `performance:${column.name}:missing-index`,
            severity: "warning",
            category: "performance",
            title: `${column.name} is not indexed`,
            explanation:
              "Foreign-key-like columns are commonly used in joins and filters. An index usually improves those lookups.",
            evidence: `No index starts with ${column.name}.`,
            recommendation: "Add an index if queries join or filter by this column.",
            sql: buildCreateIndexSql({
              tableName: tableDetail.name,
              columnName: column.name,
              indexName: buildAvailableIndexName(tableDetail, column.name),
            }),
            risk: "low",
          })
        );
      }

      if (isGenericColumnName(column)) {
        issues.push(
          makeIssue({
            id: `documentation:${column.name}:generic-name`,
            severity: "info",
            category: "documentation",
            title: `${column.name} is a generic column name`,
            explanation:
              "Generic column names hide intent and make downstream queries harder to understand.",
            evidence: `${column.name} is in the generic-name list.`,
            recommendation: "Rename or document the column purpose in the next schema cleanup.",
            fixUnavailableReason:
              "A meaningful replacement name requires domain knowledge and must not be invented by the Advisor.",
            risk: "medium",
          })
        );
      }
    });

  return issues;
}

function generateLargeTableIndexIssue(tableDetail) {
  const rowCount = Number(tableDetail.rowCount ?? 0);
  const secondaryIndexes = (tableDetail.indexes ?? []).filter((index) => index.origin !== "pk");

  if (rowCount <= 1000 || secondaryIndexes.length > 0) {
    return null;
  }

  return makeIssue({
    id: "performance:large-table-without-indexes",
    severity: "warning",
    category: "performance",
    title: "Large table has no secondary indexes",
    explanation:
      "Tables with more than 1,000 rows often need indexes on frequent filter and join columns.",
    evidence: `${tableDetail.name} has ${rowCount} rows and no secondary indexes.`,
    recommendation: "Review common queries and add indexes for WHERE, JOIN, and ORDER BY columns.",
    fixUnavailableReason:
      "Query workload information is required to choose the correct index columns without guessing.",
    risk: "low",
  });
}

function generateTableAdvisorIssues(tableDetail, columnProfiles) {
  return [
    generateMissingPrimaryKeyIssue(tableDetail),
    ...generateColumnIssues(tableDetail, columnProfiles),
    generateLargeTableIndexIssue(tableDetail),
  ]
    .filter(Boolean)
    .map((issue) => finalizeIssue(tableDetail, issue));
}

function generateProtectedTableIssue(tableDetail) {
  const isInternal = String(tableDetail.name ?? "").toLowerCase().startsWith("sqlite_");
  const kind = tableDetail.isShadow ? "shadow" : tableDetail.isVirtual ? "virtual" : "internal";
  const title = tableDetail.isShadow
    ? "Shadow table is managed internally"
    : tableDetail.isVirtual
      ? "Virtual table requires module-specific maintenance"
      : "Internal SQLite table is protected";
  const explanation = tableDetail.isShadow
    ? "This table stores implementation data for a virtual table. Direct schema or data changes can corrupt the owning virtual table."
    : tableDetail.isVirtual
      ? "Virtual table behavior and supported maintenance commands depend on the SQLite module that owns it."
      : "SQLite owns this table and may rely on its exact contents and schema.";
  const fixUnavailableReason = tableDetail.isShadow
    ? "Use the owning virtual table or its documented module commands; the Advisor will not modify a shadow table directly."
    : tableDetail.isVirtual
      ? "A generic SQL fix cannot be proven safe without module-specific maintenance rules."
      : "The Advisor never generates changes for internal SQLite tables.";

  return finalizeIssue(tableDetail, {
    id: `schema:${kind}-table:automatic-fix-unavailable`,
    severity: "info",
    category: "schema",
    title,
    explanation,
    evidence: `${tableDetail.name} is classified as a${isInternal ? "n" : ""} ${kind} table.`,
    recommendation: fixUnavailableReason,
    fixUnavailableReason,
    risk: "high",
  });
}

function calculateScore(issues = []) {
  const penalties = {
    critical: 20,
    warning: 8,
    info: 2,
  };
  const score = issues.reduce((currentScore, issue) => {
    return currentScore - (penalties[issue.severity] ?? 0);
  }, 100);

  return Math.max(0, Math.min(100, score));
}

function sortIssues(issues = []) {
  const severityOrder = {
    critical: 0,
    warning: 1,
    info: 2,
  };

  return [...issues].sort((left, right) => {
    const severityDelta = severityOrder[left.severity] - severityOrder[right.severity];

    if (severityDelta !== 0) {
      return severityDelta;
    }

    return String(left.id).localeCompare(String(right.id));
  });
}

function analyzeTable(db, tableName) {
  const tableDetail = getTableDetail(db, tableName);
  tableDetail.schemaObjectNames = db
    .prepare("SELECT name FROM sqlite_schema WHERE name IS NOT NULL")
    .all()
    .map((row) => row.name);
  const isProtectedTable =
    Boolean(tableDetail.isVirtual) ||
    Boolean(tableDetail.isShadow) ||
    String(tableDetail.name ?? "").toLowerCase().startsWith("sqlite_");
  const columnProfiles = isProtectedTable ? [] : profileTable(db, tableDetail);
  const issues = sortIssues(
    isProtectedTable
      ? [generateProtectedTableIssue(tableDetail)]
      : generateTableAdvisorIssues(tableDetail, columnProfiles)
  );

  return {
    tableName: tableDetail.name,
    score: calculateScore(issues),
    issueCount: issues.length,
    rowCount: Number(tableDetail.rowCount ?? 0),
    tableKind: tableDetail.tableKind,
    isVirtual: Boolean(tableDetail.isVirtual),
    isShadow: Boolean(tableDetail.isShadow),
    issues,
    columnProfiles,
    table: {
      columnCount: (tableDetail.columns ?? []).filter((column) => column.visible && !column.generated).length,
      indexCount: (tableDetail.indexes ?? []).length,
      foreignKeyCount: (tableDetail.foreignKeys ?? []).length,
      tableKind: tableDetail.tableKind,
      isVirtual: Boolean(tableDetail.isVirtual),
      isShadow: Boolean(tableDetail.isShadow),
    },
    analyzedAt: new Date().toISOString(),
  };
}

class TableAdvisorService {
  analyzeTable(db, tableName) {
    return analyzeTable(db, tableName);
  }
}

module.exports = {
  TableAdvisorService,
  analyzeTable,
  calculateScore,
  generateTableAdvisorIssues,
  profileTable,
  quoteIdentifier,
};
